using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Noggog;
using System.Collections.Immutable;
using System.IO;
using Mutagen.Bethesda.FormKeys.SkyrimSE;

namespace SkyrimReleveler
{
    // -------------------------------------------------------------------------
    // Data types for JSON config files
    // -------------------------------------------------------------------------
    public class ExcludedList
    {
        [JsonProperty] public List<string> Keys { get; set; } = new();
        [JsonProperty] public List<string> ForbiddenKeys { get; set; } = new();
    }

    public class RaceEntry
    {
        [JsonProperty] public List<string> Keys { get; set; } = new();
        [JsonProperty] public List<string> ForbiddenKeys { get; set; } = new();
        [JsonProperty] public short LevelModifierAdd { get; set; } = 0;
        [JsonProperty] public float LevelModifierMult { get; set; } = 1f;
    }

    public class RaceModifierList
    {
        [JsonProperty] public List<RaceEntry> Data { get; set; } = new();
    }

    public class Program
    {
        private static Lazy<Settings> _lazySettings = null!;
        private static Settings Settings => _lazySettings.Value;
        private static readonly Random Rng = new Random(42);

        public static List<string> underleveledNpcs = new();
        public static List<string> overleveledNpcs = new();
        public static List<string> highPoweredNpcs = new();

        // Classes whose NPCs are skipped during class rebuild (vendors, crafters, etc.)
        private static readonly List<string> ExcludedClasses = new()
            { "smith", "alchem", "enchant", "vendor", "apothec" };

        public static HashSet<IFormLinkGetter<INpcGetter>> npcsToIgnore = new()
        {
            Skyrim.Npc.MQ101Bear, Skyrim.Npc.WatchesTheRootsCorpse, Skyrim.Npc.BreyaCorpse,
            Skyrim.Npc.WatchesTheRoots, Skyrim.Npc.Drennen, Skyrim.Npc.Breya,
            Skyrim.Npc.dunHunterBear, Dawnguard.Npc.DLC1HowlSummonWerewolf,
        };

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "skyrim_releveled.esp")
                .Run(args);
        }

        // Priority: fixed NpcLevel first (authoritative post-TUS), then CalcMaxLevel, then CalcMinLevel.
        public static int? GetEffectiveLevel(INpcGetter npc)
        {
            switch (npc.Configuration.Level)
            {
                case INpcLevelGetter fixedLevel when fixedLevel.Level > 0:
                    return fixedLevel.Level;
                case IPcLevelMultGetter:
                    if (npc.Configuration.CalcMaxLevel > 0) return npc.Configuration.CalcMaxLevel;
                    if (npc.Configuration.CalcMinLevel > 0) return npc.Configuration.CalcMinLevel;
                    return null;
                default:
                    return null;
            }
        }

        // Stem used only for flat factions — strips prefix/suffix to get a meaningful type name.
        public static string GetStem(string editorId)
        {
            string s = editorId;
            foreach (var prefix in Settings.StripPrefixes.OrderByDescending(p => p.Length))
            {
                if (s.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                { s = s.Substring(prefix.Length); break; }
            }
            s = s.TrimEnd('0','1','2','3','4','5','6','7','8','9');
            bool stripped = true;
            while (stripped)
            {
                stripped = false;
                foreach (var suffix in Settings.StripSuffixes.OrderByDescending(x => x.Length))
                {
                    if (s.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                    {
                        s = s.Substring(0, s.Length - suffix.Length)
                             .TrimEnd('0','1','2','3','4','5','6','7','8','9');
                        stripped = true; break;
                    }
                }
            }
            if (string.IsNullOrEmpty(s)) return editorId;
            foreach (var g in Settings.GenericStemWords)
                if (s.Equals(g, StringComparison.OrdinalIgnoreCase)) return editorId;
            foreach (var sw in Settings.ShortStemExceptions)
                if (s.StartsWith(sw, StringComparison.OrdinalIgnoreCase)) return sw.ToLowerInvariant();
            return s.ToLowerInvariant();
        }

        public static (int Min, int Max) GetTrimmedRange(List<int> levels, float cutoff)
        {
            if (levels.Count == 0) return (1, 1);
            var sorted = levels.OrderBy(x => x).ToList();
            int trimCount = (int)Math.Floor(sorted.Count * cutoff);
            int lo = Math.Min(trimCount, sorted.Count - 1);
            int hi = Math.Max(sorted.Count - 1 - trimCount, lo);
            return (sorted[lo], sorted[hi]);
        }

        public static decimal MapLevel(int value, int srcMin, int srcMax, int tgtMin, int tgtMax)
        {
            int span = Math.Max(srcMax - srcMin, 1);
            decimal t = (decimal)(value - srcMin) / span;
            return Math.Round(t * (tgtMax - tgtMin) + tgtMin);
        }

        public static float GetBonusPercent(string? editorId)
        {
            if (!Settings.EnableBonusKeywords || string.IsNullOrEmpty(editorId)) return 0f;
            float best = 0f;
            foreach (var kw in Settings.BonusKeywords)
                if (!string.IsNullOrEmpty(kw.Keyword)
                    && editorId.Contains(kw.Keyword, StringComparison.OrdinalIgnoreCase)
                    && kw.BonusPercent > best)
                    best = kw.BonusPercent;
            return best;
        }

        // -------------------------------------------------------------------------
        // Skill redistribution (ported from TUS)
        // -------------------------------------------------------------------------
        private static void DistributeSkills(
            IReadOnlyDictionary<Skill, byte> skillWeights,
            IDictionary<Skill, byte> skillValues,
            int skillPoints)
        {
            float weightSum;
            bool firstPass = true;
            byte maxSkill = Settings.NPCMaxSkillLevel;
            var tempWeights = skillWeights.ToList();
            do
            {
                int overflow = 0;
                weightSum = tempWeights.Any() ? tempWeights.Sum(x => x.Value) : 0;
                for (int i = tempWeights.Count - 1; i >= 0; --i)
                {
                    if (firstPass) skillValues[tempWeights[i].Key] = 15;
                    skillValues[tempWeights[i].Key] += (byte)(skillPoints * (tempWeights[i].Value / weightSum));
                    if (skillValues[tempWeights[i].Key] > maxSkill)
                    {
                        overflow += skillValues[tempWeights[i].Key] - maxSkill;
                        skillValues[tempWeights[i].Key] = maxSkill;
                        tempWeights.RemoveAt(i);
                    }
                }
                firstPass = false;
                skillPoints = overflow;
            } while (skillPoints > 0 && weightSum > 0);
        }

        private static bool RelevelNPCSkills(Npc npc, ILinkCache linkCache)
        {
            if (Settings.NPCSkillsPerLevel <= 0) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats) && !npc.Template.IsNull)
                return false;
            if (npc.PlayerSkills is null || npc.Configuration.Level is not NpcLevel npcLevel) return false;
            if (!npc.Class.TryResolve(linkCache, out var classGetter)) return false;
            DistributeSkills(classGetter.SkillWeights, npc.PlayerSkills.SkillValues,
                (int)Math.Round(Settings.NPCSkillsPerLevel * npcLevel.Level));
            return true;
        }

        // -------------------------------------------------------------------------
        // Class rebuild (ported from TUS)
        // -------------------------------------------------------------------------
        private static void GetItemSkillWeights(IItemGetter item, IDictionary<Skill, float> w, float div = 1)
        {
            if (item is IWeaponGetter wpn && wpn.Data?.Skill is { } sk)
                w[(Skill)sk] += 1 / div;
            else if (item is IArmorGetter arm)
            {
                if (arm.HasKeyword(Skyrim.Keyword.ArmorShield)) w[Skill.Block] += 1 / div;
                if (arm.HasKeyword(Skyrim.Keyword.ArmorHeavy)) w[Skill.HeavyArmor] += 1 / div;
                else if (arm.HasKeyword(Skyrim.Keyword.ArmorLight)) w[Skill.LightArmor] += 1 / div;
            }
        }

        private static void GetLvliSkillWeights(ILeveledItemGetter lvli, IDictionary<Skill, float> w,
            ILinkCache lc, float div = 1)
        {
            var nodes = lvli.Entries?.ToList() ?? new();
            while (nodes.Any())
            {
                var n = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (n.Data is null || !n.Data.Reference.TryResolve(lc, out var entry)) continue;
                if (entry is ILeveledItemGetter sub)
                    foreach (var c in sub.Entries.EmptyIfNull()) nodes.Add(c);
                else GetItemSkillWeights(entry, w, div);
            }
        }

        private static void GetSpellSkillWeights(ISpellRecordGetter spell, IDictionary<Skill, float> w,
            ILinkCache lc, float div = 1)
        {
            if (spell is not ISpellGetter sg || sg.Type != SpellType.Spell) return;
            foreach (var eff in sg.Effects)
            {
                if (!eff.BaseEffect.TryResolve(lc, out var mgef)) continue;
                var addTo = mgef.MagicSkill switch
                {
                    ActorValue.Destruction  => (Skill?)Skill.Destruction,
                    ActorValue.Alteration   => Skill.Alteration,
                    ActorValue.Conjuration  => Skill.Conjuration,
                    ActorValue.Illusion     => Skill.Illusion,
                    ActorValue.Restoration  => Skill.Restoration,
                    _ => null
                };
                if (addTo is { } s) { w[s] += 1 / div; return; }
            }
        }

        private static void GetLvlSpellWeights(ILeveledSpellGetter lvls, IDictionary<Skill, float> w,
            ILinkCache lc, float div = 1)
        {
            var nodes = lvls.Entries?.ToList() ?? new();
            while (nodes.Any())
            {
                var n = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (n.Data is null || !n.Data.Reference.TryResolve(lc, out var entry)) continue;
                if (entry is ILeveledSpellGetter sub)
                    foreach (var c in sub.Entries.EmptyIfNull()) nodes.Add(c);
                else GetSpellSkillWeights(entry, w, lc, div);
            }
        }

        private static void PopulateByInventory(INpcSpawnGetter spawn, IDictionary<Skill, float> w, ILinkCache lc)
        {
            var nodes = new List<(INpcSpawnGetter, int)>();
            if (spawn is INpcGetter ng)
            {
                if (ng.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Inventory)
                    && ng.Template.TryResolve(lc, out var t)) nodes.Add((t, 1));
                else foreach (var e in ng.Items.EmptyIfNull())
                    if (e.Item.Item.TryResolve(lc, out var it))
                    { if (it is ILeveledItemGetter li) GetLvliSkillWeights(li, w, lc); else GetItemSkillWeights(it, w); }
            }
            else if (spawn is ILeveledNpcGetter ln)
                foreach (var e in ln.Entries.EmptyIfNull())
                    if (e.Data?.Reference.TryResolve(lc, out var s) == true) nodes.Add((s, ln.Entries!.Count));

            while (nodes.Any())
            {
                var (node, div) = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (node is ILeveledNpcGetter l2)
                    foreach (var c in l2.Entries.EmptyIfNull())
                        if (c.Data?.Reference.TryResolve(lc, out var cs) == true) nodes.Add((cs, l2.Entries!.Count));
                else if (node is INpcGetter sg2)
                {
                    if (sg2.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Inventory)
                        && sg2.Template.TryResolve(lc, out var t2)) nodes.Add((t2, 1));
                    else foreach (var e in sg2.Items.EmptyIfNull())
                        if (e.Item.Item.TryResolve(lc, out var it))
                        { if (it is ILeveledItemGetter li) GetLvliSkillWeights(li, w, lc, div); else GetItemSkillWeights(it, w, div); }
                }
            }
        }

        private static void PopulateBySpells(INpcSpawnGetter spawn, IDictionary<Skill, float> w, ILinkCache lc)
        {
            var nodes = new List<(INpcSpawnGetter, int)>();
            if (spawn is INpcGetter ng)
            {
                if (ng.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Inventory)
                    && ng.Template.TryResolve(lc, out var t)) nodes.Add((t, 1));
                else foreach (var sp in ng.ActorEffect.EmptyIfNull())
                    if (sp.TryResolve(lc, out var sr))
                    { if (sr is ILeveledSpellGetter ls) GetLvlSpellWeights(ls, w, lc); else GetSpellSkillWeights(sr, w, lc); }
            }
            else if (spawn is ILeveledNpcGetter ln)
                foreach (var e in ln.Entries.EmptyIfNull())
                    if (e.Data?.Reference.TryResolve(lc, out var s) == true) nodes.Add((s, ln.Entries!.Count));

            while (nodes.Any())
            {
                var (node, div) = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (node is ILeveledNpcGetter l2)
                    foreach (var c in l2.Entries.EmptyIfNull())
                        if (c.Data?.Reference.TryResolve(lc, out var cs) == true) nodes.Add((cs, l2.Entries!.Count));
                else if (node is INpcGetter sg2)
                {
                    if (sg2.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Inventory)
                        && sg2.Template.TryResolve(lc, out var t2)) nodes.Add((t2, 1));
                    else foreach (var sp in sg2.ActorEffect.EmptyIfNull())
                        if (sp.TryResolve(lc, out var sr))
                        { if (sr is ILeveledSpellGetter ls) GetLvlSpellWeights(ls, w, lc, div); else GetSpellSkillWeights(sr, w, lc, div); }
                }
            }
        }

        private static void PopulateByOutfit(Npc npc, IDictionary<Skill, float> w, ILinkCache lc)
        {
            if (npc.DefaultOutfit.IsNull || !npc.DefaultOutfit.TryResolve(lc, out var outfit)) return;
            foreach (var entry in outfit!.Items.EmptyIfNull())
                if (entry.TryResolve(lc, out var eg))
                {
                    if (eg is ILeveledItemGetter li) GetLvliSkillWeights(li, w, lc);
                    else if (eg is IArmorGetter arm)
                    {
                        if (arm.HasKeyword(Skyrim.Keyword.ArmorShield)) w[Skill.Block] += 1;
                        if (arm.HasKeyword(Skyrim.Keyword.ArmorHeavy)) w[Skill.HeavyArmor] += 1;
                        else if (arm.HasKeyword(Skyrim.Keyword.ArmorLight)) w[Skill.LightArmor] += 1;
                    }
                }
        }

        private static void CalculateClassWeights(Class cls, IDictionary<Skill, float> w)
        {
            var list = w.Where(e => e.Value > 0).ToList();
            list.Sort((x, y) => x.Value >= y.Value ? 1 : -1);
            float last = list[0].Value;
            for (int rank = 1, i = 0; i < list.Count; i++)
            {
                if (list[i].Value > last) { rank = i + 1; last = list[i].Value; }
                list[i] = new(list[i].Key, rank);
            }
            bool isHybrid =
                list.Any(x => x.Key is Skill.Block or Skill.OneHanded or Skill.TwoHanded or Skill.LightArmor or Skill.HeavyArmor) &&
                list.Any(x => x.Key is Skill.Illusion or Skill.Alteration or Skill.Conjuration or Skill.Destruction or Skill.Restoration);
            if (isHybrid)
            {
                float total = cls.StatWeights.Sum(x => x.Value);
                float combatSum = cls.StatWeights[BasicStat.Health] > cls.StatWeights[BasicStat.Magicka]
                    ? cls.StatWeights[BasicStat.Health] + cls.StatWeights[BasicStat.Stamina]
                    : cls.StatWeights[BasicStat.Magicka] + cls.StatWeights[BasicStat.Stamina];
                float magicSum = cls.StatWeights[BasicStat.Magicka] > cls.StatWeights[BasicStat.Health]
                    ? cls.StatWeights[BasicStat.Magicka] + cls.StatWeights[BasicStat.Stamina]
                    : cls.StatWeights[BasicStat.Health] + cls.StatWeights[BasicStat.Stamina];
                if (cls.StatWeights[BasicStat.Health] == cls.StatWeights[BasicStat.Magicka])
                    total -= cls.StatWeights[BasicStat.Stamina];
                float cr = combatSum / total, mr = magicSum / total;
                for (int i = 0; i < list.Count; i++)
                    list[i] = list[i].Key switch
                    {
                        Skill.Block or Skill.OneHanded or Skill.TwoHanded or Skill.LightArmor or Skill.HeavyArmor
                            => new(list[i].Key, (float)Math.Round(list[i].Value * cr)),
                        Skill.Illusion or Skill.Alteration or Skill.Conjuration or Skill.Destruction or Skill.Restoration
                            => new(list[i].Key, (float)Math.Round(list[i].Value * mr)),
                        _ => list[i]
                    };
            }
            list.ForEach(x => w[x.Key] = x.Value);
            if (!isHybrid && w[Skill.Block] == 0 && (w[Skill.OneHanded] > 0 || w[Skill.TwoHanded] > 0))
                w[Skill.Block] = 1;
        }

        private static bool RebalanceClassValues(Npc npc, IPatcherState<ISkyrimMod, ISkyrimModGetter> state, ILinkCache lc)
        {
            if (!Settings.RebuildNPCClasses) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats) && !npc.Template.IsNull) return false;
            if (!npc.Class.TryResolve(lc, out var cls)) return false;
            if (npc.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Unique)
                && ExcludedClasses.Any(e => (cls.EditorID?.Contains(e, StringComparison.OrdinalIgnoreCase) ?? false)
                                         || (cls.Name?.String?.Contains(e, StringComparison.OrdinalIgnoreCase) ?? false)))
                return false;

            IDictionary<Skill, float> w = new Dictionary<Skill, float>();
            cls.SkillWeights.ForEach(x => w[x.Key] = 0);
            PopulateByInventory(npc, w, lc);
            PopulateBySpells(npc, w, lc);
            PopulateByOutfit(npc, w, lc);
            w.ForEach(x => w[x.Key] = (float)Math.Ceiling(x.Value));
            if (w.All(x => x.Value == 0)) return false;

            var newClass = state.PatchMod.Classes.AddNew();
            newClass.DeepCopyIn(cls);
            newClass.EditorID = "SRClass" + npc.EditorID;
            npc.Class = newClass.ToLink();
            CalculateClassWeights(newClass, w);
            newClass.SkillWeights.ForEach(x => newClass.SkillWeights[x.Key] = 0);
            w.ForEach(x => newClass.SkillWeights[x.Key] = (byte)x.Value);
            return true;
        }

        // -------------------------------------------------------------------------
        // Perk distribution (ported from TUS)
        // -------------------------------------------------------------------------
        private static bool GetTreeFromSkill(Skill s, ILinkCache lc, out IActorValueInformationGetter? av)
        {
            av = s switch
            {
                Skill.Alchemy     => Skyrim.ActorValueInformation.AVAlchemy.TryResolve(lc),
                Skill.Alteration  => Skyrim.ActorValueInformation.AVAlteration.TryResolve(lc),
                Skill.Archery     => Skyrim.ActorValueInformation.AVMarksman.TryResolve(lc),
                Skill.Block       => Skyrim.ActorValueInformation.AVBlock.TryResolve(lc),
                Skill.Conjuration => Skyrim.ActorValueInformation.AVConjuration.TryResolve(lc),
                Skill.Destruction => Skyrim.ActorValueInformation.AVDestruction.TryResolve(lc),
                Skill.Enchanting  => Skyrim.ActorValueInformation.AVEnchanting.TryResolve(lc),
                Skill.HeavyArmor  => Skyrim.ActorValueInformation.AVHeavyArmor.TryResolve(lc),
                Skill.Illusion    => Skyrim.ActorValueInformation.AVMysticism.TryResolve(lc),
                Skill.LightArmor  => Skyrim.ActorValueInformation.AVLightArmor.TryResolve(lc),
                Skill.Lockpicking => Skyrim.ActorValueInformation.AVLockpicking.TryResolve(lc),
                Skill.OneHanded   => Skyrim.ActorValueInformation.AVOneHanded.TryResolve(lc),
                Skill.Pickpocket  => Skyrim.ActorValueInformation.AVPickpocket.TryResolve(lc),
                Skill.Restoration => Skyrim.ActorValueInformation.AVRestoration.TryResolve(lc),
                Skill.Smithing    => Skyrim.ActorValueInformation.AVSmithing.TryResolve(lc),
                Skill.Sneak       => Skyrim.ActorValueInformation.AVSneak.TryResolve(lc),
                Skill.Speech      => Skyrim.ActorValueInformation.AVSpeechcraft.TryResolve(lc),
                Skill.TwoHanded   => Skyrim.ActorValueInformation.AVTwoHanded.TryResolve(lc),
                _ => null
            };
            return av is not null;
        }

        private static bool PerformCompare<T>(IConditionGetter? c, T l, T r) where T : IComparable<T>
            => c?.CompareOperator switch
            {
                CompareOperator.EqualTo              => l.CompareTo(r) == 0,
                CompareOperator.GreaterThan          => l.CompareTo(r) > 0,
                CompareOperator.GreaterThanOrEqualTo => l.CompareTo(r) >= 0,
                CompareOperator.LessThan             => l.CompareTo(r) < 0,
                CompareOperator.LessThanOrEqualTo    => l.CompareTo(r) <= 0,
                CompareOperator.NotEqualTo           => l.CompareTo(r) != 0,
                _ => false
            };

        private static void RemoveVanillaPerks(Npc npc, ILinkCache vanillaCache)
        {
            if (npc.Perks is null || npc.Perks.Count == 0) return;
            for (int i = npc.Perks.Count - 1; i >= 0; --i)
            {
                if (npc.Perks[i].Perk.Equals(Skyrim.Perk.AlchemySkillBoosts) ||
                    npc.Perks[i].Perk.Equals(Skyrim.Perk.PerkSkillBoosts)) continue;
                if (vanillaCache.TryResolve<IPerkGetter>(npc.Perks[i].Perk, out _))
                    npc.Perks.RemoveAt(i);
            }
        }

        private static bool FulfillsPerkConditions(Npc npc, IPerkGetter perk, Skill skill, ILinkCache lc)
        {
            if (npc.Perks!.Any(x => x.Perk.Equals(perk.ToLink()))) return false;
            foreach (var cond in perk.Conditions)
            {
                if (cond is not ConditionFloat cf) continue;
                if (cf.Data is GetBaseActorValueConditionData avd && (int)avd.ActorValue == (int)skill)
                { if (!PerformCompare(cf, npc.PlayerSkills!.SkillValues[skill], cf.ComparisonValue)) return false; }
                else if (cf.Data is HasPerkConditionData pd && pd.Perk.Link.TryResolve(lc, out var req))
                {
                    bool has = npc.Perks!.Any(x => x.Perk.Equals(req.ToLink()));
                    if ((cf.CompareOperator == CompareOperator.EqualTo    && cf.ComparisonValue == 1 && !has) ||
                        (cf.CompareOperator == CompareOperator.NotEqualTo && cf.ComparisonValue == 1 && has)  ||
                        (cf.CompareOperator == CompareOperator.EqualTo    && cf.ComparisonValue == 0 && has)  ||
                        (cf.CompareOperator == CompareOperator.NotEqualTo && cf.ComparisonValue == 0 && !has))
                        return false;
                }
                else return false;
            }
            return true;
        }

        private static bool DistributeNPCPerks(Npc npc, ILinkCache lc, ILinkCache vanillaCache,
            ExcludedList excludedPerks)
        {
            if (Settings.NPCPerksPerLevel <= 0) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.SpellList) && !npc.Template.IsNull) return false;
            if (npc.PlayerSkills is null) return false;
            if (!npc.Class.TryResolve<IClassGetter>(lc, out var cls)) return false;
            if (!npc.Race.TryResolve<IRaceGetter>(lc, out var race)) return false;
            if (!race.HasKeyword(Skyrim.Keyword.ActorTypeNPC) && !race.HasKeyword(Skyrim.Keyword.ActorTypeUndead)) return false;
            // Check keyword filter
            foreach (var kw in Settings.PerkDistributionFilter)
                if (npc.HasKeyword(kw) || race.HasKeyword(kw)) return false;

            float perksTotal = Settings.NPCPerksPerLevel;
            if (npc.Configuration.Level is NpcLevel nl) perksTotal *= nl.Level;

            npc.Perks ??= new();
            if (Settings.RemoveVanillaPerks) RemoveVanillaPerks(npc, vanillaCache);

            int overflow = 0;
            var perkDist = cls.SkillWeights.ToList();
            float wSum = perkDist.Any() ? perkDist.Sum(x => x.Value) : 0;

            foreach (var pw in perkDist)
            {
                if (pw.Value <= 0) continue;
                byte toSpend = (byte)Math.Round(overflow + perksTotal * (pw.Value / wSum));
                if (toSpend <= 0) continue;
                if (!GetTreeFromSkill(pw.Key, lc, out var tree) || tree!.PerkTree is null) continue;

                while (toSpend > 0)
                {
                    bool added = false;
                    foreach (var node in tree.PerkTree)
                    {
                        if (toSpend <= 0) break;
                        if (!node.Perk.TryResolve(lc, out var perkEntry) || perkEntry.EditorID is null) continue;
                        if (excludedPerks.Keys.Any(k => perkEntry.EditorID.Contains(k, StringComparison.OrdinalIgnoreCase)) &&
                            !excludedPerks.ForbiddenKeys.Any(k => perkEntry.EditorID.Contains(k, StringComparison.OrdinalIgnoreCase))) continue;
                        if (FulfillsPerkConditions(npc, perkEntry, pw.Key, lc))
                        {
                            --toSpend; added = true;
                            npc.Perks!.Add(new PerkPlacement { Perk = perkEntry.ToLink(), Rank = 1 });
                        }
                        while (toSpend > 0 && perkEntry.NextPerk.TryResolve<IPerkGetter>(lc, out perkEntry))
                        {
                            if (FulfillsPerkConditions(npc, perkEntry, pw.Key, lc))
                            { --toSpend; added = true; npc.Perks!.Add(new PerkPlacement { Perk = perkEntry.ToLink(), Rank = 1 }); }
                            else break;
                        }
                    }
                    if (!added) { overflow = toSpend; break; }
                    else overflow = 0;
                }
            }
            if (npc.Perks.Count == 0) npc.Perks = null;
            return true;
        }

        private static void DisableExtraDamagePerks(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (!Settings.DisableExtraDamagePerks) return;
            foreach (var perkGetter in state.LoadOrder.PriorityOrder.Perk().WinningOverrides()
                .Where(x => x.EditorID?.Contains("crExtraDamage", StringComparison.OrdinalIgnoreCase) == true))
            {
                var perk = state.PatchMod.Perks.GetOrAddAsOverride(perkGetter);
                perk.Effects.Clear();
            }
        }

        // -------------------------------------------------------------------------
        // RunPatch
        // -------------------------------------------------------------------------
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (state.ExtraSettingsDataPath is null)
            { Console.Error.WriteLine("ERROR: ExtraSettingsDataPath is null."); return; }

            // Load enemy rules
            var rulesPath = Path.Combine(state.ExtraSettingsDataPath, "enemy_rules.json");
            if (!File.Exists(rulesPath)) { Console.Error.WriteLine($"ERROR: Missing {rulesPath}"); return; }
            var rulesJson = File.ReadAllText(rulesPath);
            var enemyRules = JsonConvert.DeserializeObject<Dictionary<string, int[]>>(rulesJson,
                new JsonSerializerSettings { Error = (s, a) => a.ErrorContext.Handled = true })!;
            // Preserve JSON order, use Contains matching for faction IDs
            var orderedRules = JObject.Parse(rulesJson).Properties()
                .Where(p => enemyRules.ContainsKey(p.Name))
                .Select(p => (Faction: p.Name, Rule: enemyRules[p.Name]))
                .ToList();
            Console.WriteLine($"Loaded {orderedRules.Count} faction rules.");

            // Load named NPC overrides
            var namedPath = Path.Combine(state.ExtraSettingsDataPath, "named_npcs.json");
            if (!File.Exists(namedPath)) { Console.Error.WriteLine($"ERROR: Missing {namedPath}"); return; }
            var namedNpcs = JsonConvert.DeserializeObject<Dictionary<string, int>>(File.ReadAllText(namedPath),
                new JsonSerializerSettings { Error = (s, a) => a.ErrorContext.Handled = true }) ?? new();
            Console.WriteLine($"Loaded {namedNpcs.Count} named NPC overrides.");

            // Load custom followers
            var followersPath = Path.Combine(state.ExtraSettingsDataPath, "customFollowers.json");
            var customFollowers = File.Exists(followersPath)
                ? JsonConvert.DeserializeObject<FollowerList>(File.ReadAllText(followersPath)) ?? new()
                : new FollowerList();

            // Load excluded NPCs
            var exclNpcsPath = Path.Combine(state.ExtraSettingsDataPath, "excludedNPCs.json");
            var excludedNPCs = File.Exists(exclNpcsPath)
                ? JsonConvert.DeserializeObject<ExcludedList>(File.ReadAllText(exclNpcsPath)) ?? new()
                : new ExcludedList();

            // Load excluded perks
            var exclPerksPath = Path.Combine(state.ExtraSettingsDataPath, "excludedPerks.json");
            var excludedPerks = File.Exists(exclPerksPath)
                ? JsonConvert.DeserializeObject<ExcludedList>(File.ReadAllText(exclPerksPath)) ?? new()
                : new ExcludedList();

            // Load race level modifiers
            var racePath = Path.Combine(state.ExtraSettingsDataPath, "raceLevelModifiers.json");
            var raceModifiers = File.Exists(racePath)
                ? JsonConvert.DeserializeObject<RaceModifierList>(File.ReadAllText(racePath)) ?? new()
                : new RaceModifierList();

            // Vanilla-only link cache for perk removal — only loaded if actually needed.
            ILinkCache? vanillaCache = null;
            ILinkCache GetVanillaCache() => vanillaCache ??= LoadOrder.Import<ISkyrimModGetter>(
                state.DataFolderPath,
                new List<ModKey> { Skyrim.ModKey, Dawnguard.ModKey, Dragonborn.ModKey },
                GameRelease.SkyrimSE).ToImmutableLinkCache();

            Console.WriteLine("Data files loaded. Starting patch...");

            // Build a single immutable link cache used for the entire patch — same as TUS's Patcher.LinkCache.
            // Much faster than using state.LinkCache which rebuilds on each access in newer Mutagen.
            var linkCache = state.LoadOrder.PriorityOrder.ToImmutableLinkCache();

            // --- Helpers ---
            static List<string> SplitTokens(string s)
            {
                var tokens = new List<string>(); int start = 0;
                for (int i = 1; i <= s.Length; i++)
                {
                    bool b = i == s.Length
                        || (char.IsUpper(s[i]) && i > 0 && char.IsLower(s[i-1]))
                        || (char.IsUpper(s[i]) && i+1 < s.Length && char.IsLower(s[i+1]) && char.IsUpper(s[i-1]))
                        || (char.IsDigit(s[i]) != char.IsDigit(s[i-1]));
                    if (b) { var t = s.Substring(start, i - start); if (t.Length > 0) tokens.Add(t); start = i; }
                }
                return tokens;
            }

            int? FindNamedLevel(string? editorId)
            {
                if (string.IsNullOrEmpty(editorId)) return null;
                var et = SplitTokens(editorId);
                foreach (var (key, level) in namedNpcs)
                {
                    var kt = SplitTokens(key);
                    if (kt.Count == 0) continue;
                    for (int i = 0; i <= et.Count - kt.Count; i++)
                    {
                        bool match = true;
                        for (int j = 0; j < kt.Count; j++)
                            if (!string.Equals(et[i+j], kt[j], StringComparison.OrdinalIgnoreCase)) { match = false; break; }
                        if (match) return level;
                    }
                }
                return null;
            }

            bool IsExcluded(string editorId) =>
                excludedNPCs.Keys.Any(k => editorId.Contains(k, StringComparison.OrdinalIgnoreCase)) &&
                !excludedNPCs.ForbiddenKeys.Any(k => editorId.Contains(k, StringComparison.OrdinalIgnoreCase));

            bool IsFollower(INpcGetter npc)
            {
                if (!Settings.ScaleFollowers || npc.EditorID is null) return false;
                if (npc.Factions.Any(f => f.Faction.Equals(Skyrim.Faction.PotentialFollowerFaction) ||
                                          f.Faction.Equals(Skyrim.Faction.PotentialHireling))) return true;
                foreach (var entry in customFollowers.Followers)
                {
                    if (string.IsNullOrEmpty(entry.Key)) continue;
                    if (!npc.EditorID.Contains(entry.Key, StringComparison.OrdinalIgnoreCase)) continue;
                    if (entry.ForbiddenKeys.Any(fk => npc.EditorID.Contains(fk, StringComparison.OrdinalIgnoreCase))) continue;
                    return true;
                }
                return false;
            }

            void GetRaceModifier(INpcGetter npc, out short add, out float mult)
            {
                add = 0; mult = 1f;
                if (!npc.Race.TryResolve(linkCache, out var race) || race.EditorID is null) return;
                foreach (var entry in raceModifiers.Data)
                    if (entry.Keys.Any(k => race.EditorID.Contains(k, StringComparison.OrdinalIgnoreCase)) &&
                        !entry.ForbiddenKeys.Any(k => race.EditorID.Contains(k, StringComparison.OrdinalIgnoreCase)))
                    { add = entry.LevelModifierAdd; mult = entry.LevelModifierMult; return; }
            }

            // --- Single discovery pass: collect levels, stems, and cache faction match per NPC ---
            // npcFactionCache[formKey] = (matchedFactionKey, effectiveLevel)
            var npcFactionCache = new Dictionary<FormKey, (string Faction, int EffLevel)>();
            var factionAllLevels = new Dictionary<string, List<int>>();
            var flatFactionStems = new Dictionary<string, List<string>>();

            foreach (var getter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                if (npcsToIgnore.Contains(getter)) continue;
                if (getter.EditorID is not { } edId) continue;
                if (getter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.IsCharGenFacePreset) ||
                    getter.HasKeyword(Skyrim.Keyword.PlayerKeyword)) continue;
                if (IsExcluded(edId)) continue;
                if (FindNamedLevel(edId) is not null) continue;
                if (IsFollower(getter)) continue;
                int? eff = GetEffectiveLevel(getter);
                if (eff is null) continue;

                string? firstMatchedKey = null;
                foreach (var rank in getter.Factions)
                {
                    if (!rank.Faction.TryResolve(linkCache, out var fac) || fac.EditorID is null) continue;
                    var matchedKey = orderedRules.FirstOrDefault(r =>
                        fac.EditorID.Contains(r.Faction, StringComparison.OrdinalIgnoreCase)).Faction;
                    if (matchedKey is null) continue;

                    // Collect levels for source range calculation
                    if (!factionAllLevels.TryGetValue(matchedKey, out var lst))
                        factionAllLevels[matchedKey] = lst = new List<int>();
                    lst.Add(eff.Value);

                    // Cache the first (highest priority) faction match for Pass 2
                    firstMatchedKey ??= matchedKey;
                }

                if (firstMatchedKey is not null)
                    npcFactionCache[getter.FormKey] = (firstMatchedKey, eff.Value);
            }

            var flatFactions = new HashSet<string>(
                factionAllLevels.Where(kvp => kvp.Value.Distinct().Count() == 1).Select(kvp => kvp.Key));

            var factionSourceRange = new Dictionary<string, (int Min, int Max)>();
            float cutoff = Settings.OutlierPercentileCutoff;
            foreach (var (fId, lvls) in factionAllLevels)
                if (!flatFactions.Contains(fId))
                    factionSourceRange[fId] = GetTrimmedRange(lvls, cutoff);

            // Collect stems for flat factions — only needs a second pass over the already-cached NPCs
            foreach (var (formKey, cached) in npcFactionCache)
            {
                if (!flatFactions.Contains(cached.Faction)) continue;
                if (!linkCache.TryResolve<INpcGetter>(formKey, out var npcGetter) || npcGetter.EditorID is null) continue;
                if (!flatFactionStems.TryGetValue(cached.Faction, out var stems))
                    flatFactionStems[cached.Faction] = stems = new List<string>();
                string stem = GetStem(npcGetter.EditorID);
                if (!stems.Contains(stem)) stems.Add(stem);
            }

            if (Settings.PrintDebugOutput)
            {
                foreach (var (fId, stems) in flatFactionStems)
                    Console.WriteLine($"Flat faction {fId}: {stems.Count} stems: {string.Join(", ", stems)}");
                foreach (var (fId, range) in factionSourceRange.OrderBy(x => x.Key))
                    Console.WriteLine($"Non-flat faction {fId}: source [{range.Min},{range.Max}] ({factionAllLevels[fId].Count} members)");
            }

            // --- Pass 2: relevel + redistribute skills/perks ---
            // Uses DeepCopy+Set pattern (same as TUS) — avoids GetOrAddAsOverride overhead.
            int followersScaled = 0, npcsProcessed = 0;
            foreach (var getter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                if (npcsToIgnore.Contains(getter)) continue;
                if (getter.EditorID is not { } editorId) continue;
                if (getter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.IsCharGenFacePreset) ||
                    getter.HasKeyword(Skyrim.Keyword.PlayerKeyword)) continue;
                if (IsExcluded(editorId)) continue;

                bool wasChanged = false;
                Npc npcCopy = getter.DeepCopy();

                // Followers — unlimited PC-level scaling, skip releveling
                if (IsFollower(getter))
                {
                    npcCopy.Configuration.Level = new PcLevelMult { LevelMult = 1f };
                    npcCopy.Configuration.CalcMinLevel = Math.Max(npcCopy.Configuration.CalcMinLevel, (short)1);
                    npcCopy.Configuration.CalcMaxLevel = short.MaxValue;
                    ++followersScaled;
                    wasChanged = true;
                    if (Settings.PrintDebugOutput) Console.WriteLine($"  {editorId}: follower -> unlimited scaling");
                    state.PatchMod.Npcs.Set(npcCopy);
                    continue;
                }

                // Named NPC override
                int? namedLevel = FindNamedLevel(editorId);
                if (namedLevel is not null)
                {
                    GetRaceModifier(getter, out var rAdd, out var rMult);
                    short fixedLevel = (short)Math.Clamp(
                        Math.Round(namedLevel.Value * rMult) + rAdd + Settings.GlobalOffset, 1, short.MaxValue);
                    if (Settings.PrintDebugOutput) Console.WriteLine($"  {editorId}: named -> {fixedLevel}");
                    ApplyLevel(npcCopy, fixedLevel);
                    RebalanceClassValues(npcCopy, state, linkCache);
                    RelevelNPCSkills(npcCopy, linkCache);
                    wasChanged |= DistributeNPCPerks(npcCopy, linkCache, GetVanillaCache(), excludedPerks);
                    wasChanged = true;
                    state.PatchMod.Npcs.Set(npcCopy);
                    continue;
                }

                // Find matching faction rule — use cache from discovery pass
                if (!npcFactionCache.TryGetValue(getter.FormKey, out var cached))
                    continue;

                int[]? rule = enemyRules.TryGetValue(cached.Faction, out var r) ? r : null;
                string matchedFaction = cached.Faction;
                if (rule is null) continue;

                int effectiveLevel = cached.EffLevel;
                int targetMin = rule[0], targetMax = rule[1];
                if (effectiveLevel > targetMax)
                {
                    if (Settings.PrintDebugOutput) Console.WriteLine($"  {editorId}: eff {effectiveLevel} > {targetMax}, skipping.");
                    continue;
                }

                // Compute base target level
                decimal baseLevel;
                if (flatFactions.Contains(matchedFaction))
                {
                    string stem = GetStem(editorId);
                    var stems = flatFactionStems.TryGetValue(matchedFaction, out var sl) ? sl : new List<string>();
                    int count = Math.Max(stems.Count, 1);
                    int idx = Math.Max(stems.IndexOf(stem), 0);
                    int bandSize = Math.Max((targetMax - targetMin) / count, 1);
                    int bandMin = targetMin + idx * bandSize;
                    int bandMax = idx == count - 1 ? targetMax : bandMin + bandSize - 1;
                    baseLevel = Rng.Next(bandMin, bandMax + 1) + Settings.GlobalOffset;
                    if (Settings.PrintDebugOutput)
                        Console.WriteLine($"  {editorId} [stem:{stem} {idx+1}/{count}]: flat -> band [{bandMin},{bandMax}] -> {baseLevel}");
                }
                else
                {
                    (int srcMin, int srcMax) = factionSourceRange[matchedFaction];
                    int clamped = Math.Clamp(effectiveLevel, srcMin, srcMax);
                    if (effectiveLevel < srcMin) underleveledNpcs.Add(editorId);
                    if (effectiveLevel > srcMax) overleveledNpcs.Add(editorId);
                    baseLevel = MapLevel(clamped, srcMin, srcMax, targetMin, targetMax) + Settings.GlobalOffset;
                    if (Settings.PrintDebugOutput)
                        Console.WriteLine($"  {editorId}: eff {effectiveLevel} in [{srcMin},{srcMax}] -> [{targetMin},{targetMax}] -> {baseLevel}");
                }

                // Apply race modifier and boss bonus
                GetRaceModifier(getter, out var add, out var mult);
                baseLevel = Math.Round(baseLevel * (decimal)mult) + add;
                float bonusPct = GetBonusPercent(editorId);
                if (bonusPct > 0f) baseLevel = Math.Round(baseLevel * (decimal)(1f + bonusPct / 100f));

                short newLevel = (short)Math.Clamp(baseLevel, 1, short.MaxValue);
                if (newLevel > 100) highPoweredNpcs.Add(editorId);

                ApplyLevel(npcCopy, newLevel);
                RebalanceClassValues(npcCopy, state, linkCache);
                RelevelNPCSkills(npcCopy, linkCache);
                DistributeNPCPerks(npcCopy, linkCache, GetVanillaCache(), excludedPerks);
                state.PatchMod.Npcs.Set(npcCopy);

                ++npcsProcessed;
                if (npcsProcessed % 500 == 0) Console.WriteLine($"Processed {npcsProcessed} NPCs...");
            }

            DisableExtraDamagePerks(state);
            Console.WriteLine($"Done. {npcsProcessed} NPCs releveled, {followersScaled} followers scaled.");
            PrintWarnings();
        }

        public static void ApplyLevel(INpc npc, short newLevel)
        {
            npc.Configuration.Level = new NpcLevel() { Level = newLevel };
            npc.Configuration.CalcMinLevel = 1;
            npc.Configuration.CalcMaxLevel = newLevel;
        }

        public static IEnumerable<INpcGetter> ResolveStatsRoots(
            INpcGetter npc, ILinkCache lc, HashSet<FormKey> visited)
        {
            if (!visited.Add(npc.FormKey)) yield break;
            if (!npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats)
                || npc.Template.IsNull
                || !npc.Template.TryResolve(lc, out var template))
            { yield return npc; yield break; }
            foreach (var root in ResolveSpawnRoots(template, lc, visited))
                yield return root;
        }

        private static IEnumerable<INpcGetter> ResolveSpawnRoots(
            INpcSpawnGetter spawn, ILinkCache lc, HashSet<FormKey> visited)
        {
            switch (spawn)
            {
                case INpcGetter npc:
                    foreach (var root in ResolveStatsRoots(npc, lc, visited)) yield return root;
                    break;
                case ILeveledNpcGetter leveled:
                    if (!visited.Add(leveled.FormKey)) break;
                    foreach (var entry in leveled.Entries.EmptyIfNull())
                    {
                        if (entry.Data is not { } data) continue;
                        if (!data.Reference.TryResolve(lc, out var ref2)) continue;
                        foreach (var root in ResolveSpawnRoots(ref2, lc, visited)) yield return root;
                    }
                    break;
            }
        }

        public static void PrintWarnings()
        {
            if (underleveledNpcs.Count > 0)
            {
                Console.WriteLine("Warning: NPCs below faction trimmed minimum, pinned to target minimum:");
                foreach (var item in underleveledNpcs) Console.WriteLine("  " + item);
            }
            if (overleveledNpcs.Count > 0)
            {
                Console.WriteLine("Warning: NPCs above faction trimmed maximum, pinned to target maximum:");
                foreach (var item in overleveledNpcs) Console.WriteLine("  " + item);
            }
            if (highPoweredNpcs.Count > 0)
            {
                Console.WriteLine("Warning: NPCs assigned level > 100:");
                foreach (var item in highPoweredNpcs) Console.WriteLine("  " + item);
            }
        }
    }
}
