using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Newtonsoft.Json;
using Noggog;

namespace SkyrimReleveler
{
    public class ExcludedList
    {
        [JsonProperty] public List<string> Keys { get; set; } = new();
        [JsonProperty] public List<string> ForbiddenKeys { get; set; } = new();
    }

    public static class TierSystem
    {
        public const int Count = 15;

        // Base ranges at WorldMaxLevel = 1000. Scaled proportionally at runtime.
        private static readonly (int Min, int Max)[] BaseRanges = new (int, int)[]
        {
            (800, 1000), // 0  Cosmic
            (600,  800), // 1  World-ender
            (350,  600), // 2  Dragon
            (250,  450), // 3  Ancient Lich / Dragon Priest
            (200,  380), // 4  High Daedra
            (160,  300), // 5  Vampire Lord / Soul Cairn
            (140,  260), // 6  Elite Construct
            (100,  200), // 7  Falmer / Mid Daedra / Giant
            ( 80,  180), // 8  Vampire / Gargoyle / Werewolf
            ( 60,  140), // 9  Draugr / Atronach / Skeleton Lord
            ( 45,  110), // 10 Spriggan / Hagrave / Troll
            ( 30,   80), // 11 Dangerous Wildlife
            ( 35,  120), // 12 Humanoid Enemy
            ( 10,   60), // 13 Standard Creature
            (  1,   20), // 14 Vermin / Passive Animal
        };

        private static readonly string[] Names = new[]
        {
            "Cosmic", "World-ender", "Dragon", "Ancient Lich / Dragon Priest",
            "High Daedra", "Vampire Lord / Soul Cairn", "Elite Construct",
            "Falmer / Mid Daedra / Giant", "Vampire / Gargoyle / Werewolf",
            "Draugr / Atronach / Skeleton Lord", "Spriggan / Hagrave / Troll",
            "Dangerous Wildlife", "Humanoid Enemy", "Standard Creature", "Vermin / Passive Animal",
        };

        public static (int Min, int Max) GetRange(int tier, int worldMaxLevel)
        {
            var (bMin, bMax) = BaseRanges[tier];
            double scale = worldMaxLevel / 1000.0;
            return ((int)Math.Round(bMin * scale), (int)Math.Round(bMax * scale));
        }

        public static string GetName(int tier) => Names[tier];

        // Highest vanilla level assigned to a generic NPC in each tier.
        // Used as the anchor when no peer group is available.
        private static readonly int[] VanillaCeilings = new int[]
        {
            150, // 0  Cosmic
            100, // 1  World-ender
             75, // 2  Dragon
             50, // 3  Dragon Priest
             46, // 4  High Daedra
             50, // 5  Vampire Lord
             36, // 6  Elite Construct
             46, // 7  Falmer / Mid Daedra
             53, // 8  Vampire / Werewolf
             45, // 9  Draugr / Atronach
             28, // 10 Spriggan / Troll
             38, // 11 Dangerous Wildlife
             50, // 12 Humanoid Enemy
             20, // 13 Standard Creature
              8, // 14 Vermin
        };

        public static int GetVanillaCeiling(int tier) => VanillaCeilings[tier];
    }

    public class NpcAssessment
    {
        public FormKey FormKey { get; set; }
        public string EditorId { get; set; } = "";
        public int Tier { get; set; } = 12;
        public int SourceLevel { get; set; }        // CalcMax or fixed level; 0 = none
        public string? FactionKey { get; set; }
        public FormKey RaceFormKey { get; set; }
        public ModKey ModKey { get; set; }
    }

    public class Program
    {
        private static Lazy<Settings> _lazySettings = null!;
        private static Settings Settings => _lazySettings.Value;

        private static readonly List<string> CivilianClassTerms = new()
        {
            "smith", "alchem", "enchant", "vendor", "apothec",
            "innkeep", "merchant", "farmer", "miner", "beggar",
            "priest", "bard", "jarl", "steward"
        };

        private static readonly List<string> ExcludedClasses = new()
            { "smith", "alchem", "enchant", "vendor", "apothec" };

        public static HashSet<IFormLinkGetter<INpcGetter>> NpcsToIgnore = new()
        {
            Skyrim.Npc.MQ101Bear, Skyrim.Npc.WatchesTheRootsCorpse, Skyrim.Npc.BreyaCorpse,
            Skyrim.Npc.WatchesTheRoots, Skyrim.Npc.Drennen, Skyrim.Npc.Breya,
            Skyrim.Npc.dunHunterBear, Dawnguard.Npc.DLC1HowlSummonWerewolf,
        };

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "skyrim_releveled.esp")
                .Run(args);
        }

        // Returns the authored level to use as this NPC's source.
        // CalcMax > 0 wins; otherwise fixed level; otherwise 0 (no authored level).
        public static int GetSourceLevel(INpcGetter npc)
        {
            if (npc.Configuration.CalcMaxLevel > 0)
                return npc.Configuration.CalcMaxLevel;
            if (npc.Configuration.Level is INpcLevelGetter fl && fl.Level > 0)
                return fl.Level;
            return 0;
        }

        private static bool ContainsAny(string? s, params string[] patterns)
        {
            if (s is null) return false;
            foreach (var p in patterns)
                if (s.Contains(p, StringComparison.OrdinalIgnoreCase)) return true;
            return false;
        }

        // -------------------------------------------------------------------------
        // Tier classification — unchanged from original
        // -------------------------------------------------------------------------
        public static int ClassifyNpc(INpcGetter npc, ILinkCache lc)
        {
            string? editorId    = npc.EditorID;
            string? npcName     = npc.Name?.String;
            string? raceEditorId = null;

            if (npc.Race.TryResolve(lc, out var race))
                raceEditorId = race.EditorID;

            int tier = ClassifyByRaceKeyword(race, raceEditorId);
            tier = ApplyNpcNameOverrides(tier, editorId, npcName);
            tier = ApplyNpcKeywordOverrides(npc, tier, lc);
            tier = ApplyClassOverrides(npc, tier, lc);
            return tier;
        }

        private static int ApplyClassOverrides(INpcGetter npc, int currentTier, ILinkCache lc)
        {
            if (!npc.Class.TryResolve(lc, out var cls)) return currentTier;
            string clsId = cls.EditorID ?? "";

            if (ContainsAny(clsId, "MolagBal","Jyggalag","DaedricPrince","Akatosh",
                                   "Mehrunes","Azura","Boethiah","Mephala","Meridia",
                                   "Nocturnal","Malacath","Peryite","Sanguine","Sheogorath",
                                   "Vaermina","Clavicus","Namira","Hircine","Hermaeus"))
                return Math.Min(currentTier, 0);
            if (ContainsAny(clsId, "Alduin","WorldEater","WorldEnder"))
                return Math.Min(currentTier, 1);
            if (ContainsAny(clsId, "Dragon") && !ContainsAny(clsId, "DragonPriest"))
                return Math.Min(currentTier, 2);
            if (ContainsAny(clsId, "DragonPriest","Lich","AyleidLich","NecroLich"))
                return Math.Min(currentTier, 3);
            if (ContainsAny(clsId, "Dremora","Xivilai","GoldenSaint","DarkSeducer"))
                return Math.Min(currentTier, 4);
            if (ContainsAny(clsId, "VampireLord","SoulCairn","IdealMaster"))
                return Math.Min(currentTier, 5);
            if (ContainsAny(clsId, "Centurion","DwarvenCenturion","DweForgemaster"))
                return Math.Min(currentTier, 6);
            return currentTier;
        }

        private static int ClassifyByRaceKeyword(IRaceGetter? race, string? raceEditorId)
        {
            if (race is null) return 12;

            if (race.HasKeyword(Skyrim.Keyword.ActorTypeDragon))   return ClassifyDragon(raceEditorId);
            if (race.HasKeyword(Skyrim.Keyword.ActorTypeDaedra))   return ClassifyDaedra(raceEditorId);
            if (race.HasKeyword(Skyrim.Keyword.ActorTypeUndead))   return ClassifyUndead(raceEditorId);
            if (race.HasKeyword(Skyrim.Keyword.ActorTypeDwarven))  return ClassifyConstruct(raceEditorId);
            if (race.HasKeyword(Skyrim.Keyword.ActorTypeGhost))    return 9;

            if (ContainsAny(race.EditorID, "Werewolf","Werebear","Werebat")) return 8;

            if (race.HasKeyword(Skyrim.Keyword.ActorTypeNPC))      return ClassifyHumanoid(raceEditorId);
            if (race.HasKeyword(Skyrim.Keyword.ActorTypeAnimal))   return ClassifyAnimalOrCreature(raceEditorId, isForcedAnimal: true);
            if (race.HasKeyword(Skyrim.Keyword.ActorTypeCreature)) return ClassifyAnimalOrCreature(raceEditorId, isForcedAnimal: false);

            return ClassifyAnimalOrCreature(raceEditorId, isForcedAnimal: false);
        }

        private static int ClassifyDragon(string? raceId)
        {
            if (raceId is null) return 2;
            if (raceId.Equals("AlduinRace", StringComparison.OrdinalIgnoreCase)) return 1;
            if (ContainsAny(raceId, "DragonPriest")) return 3;
            return 2;
        }

        private static int ClassifyDaedra(string? raceId)
        {
            if (raceId is null) return 4;
            if (ContainsAny(raceId, "Dremora","Xivilai","Xivkyn","GoldenSaint","DarkSeducer",
                                    "Auroran","KnightOfOrder","OrderKnight","OrderPriest",
                                    "Hunger","FleshAtronach","IronAtronach","EarthAtronach"))
                return 4;
            if (ContainsAny(raceId, "Scamp","Clannfear","Daedroth","Grummite","Balliwog",
                                    "Banekin","SpiderDaedra","Watcher"))
                return 7;
            return 4;
        }

        private static int ClassifyUndead(string? raceId)
        {
            if (raceId is null) return 9;
            if (ContainsAny(raceId, "VampireLord","VampireBeast","SoulCairn",
                                    "IdealMaster","VampireBones")) return 5;
            if (ContainsAny(raceId, "Lich","DragonPriest","BoneLord",
                                    "EbonyPriest","WraithKnight","WraithLord",
                                    "WraithWitch","WraithArchwitch")) return 3;
            if (ContainsAny(raceId, "HulkingDraugr","DraugrJyrik","DraugrGiant",
                                    "SkeletonGoliath","BoneColossus","BoneHulk",
                                    "ShamblesLord")) return 6;
            return 9;
        }

        private static int ClassifyConstruct(string? raceId)
        {
            if (raceId is null) return 9;
            if (ContainsAny(raceId, "Centurion","Forgemaster","Colossus","Golem",
                                    "Driller","Pretorian","GoldBoneCenturion",
                                    "DweKnight","DweQueen","DweSoldier")) return 6;
            return 9;
        }

        private static int ClassifyHumanoid(string? raceId)
        {
            if (raceId is null) return 12;
            if (ContainsAny(raceId, "SnowElf","Falmer","Nerevarine","Chimera")) return 7;
            return 12;
        }

        private static int ClassifyAnimalOrCreature(string? raceId, bool isForcedAnimal)
        {
            if (raceId is null) return isForcedAnimal ? 14 : 13;

            if (ContainsAny(raceId, "Mammoth","Giant","Troll","Hagrave","Spriggan",
                                    "Chaurus","Falmer","Lurker","Dreugh",
                                    "Griffon","Gorgon","Minotaur","Ogre","CaveWorm",
                                    "Wendigo","Elytra","Scalon","FleshGuardian",
                                    "BirdMan","HalfDragon"))
                return 7;

            if (ContainsAny(raceId, "Wispmother","WillOWisp","WillOtheWisp")) return 10;

            if (ContainsAny(raceId, "Bear","Sabrecat","Wolf","Spider","DeathHound",
                                    "Gargoyle","IceWraith","Wisp",
                                    "Raptor","Panther","Lion","Hyena","Tiger",
                                    "DeathWeaver","NightmareHound","SpiritHound",
                                    "FrostHound","Nekker","Horker","Slaughterfish",
                                    "Mudcrab","Frostbite","Skeever","Riekling"))
                return 11;

            if (ContainsAny(raceId, "Skeever","Rat","Dog","Horse","Goat","Sheep",
                                    "Cow","Chicken","Rabbit","Deer","Elk",
                                    "Fox","Hare","Pig","Goose","Crab",
                                    "Reindeer","Netch","Boar"))
                return 14;

            if (isForcedAnimal) return 14;
            return 13;
        }

        private static int ApplyNpcNameOverrides(int currentTier, string? editorId, string? name)
        {
            if (ContainsAny(editorId, "MolagBal","Jyggalag","Shoggoth","DaedricPrince","MolagInner") ||
                ContainsAny(name,     "Molag Bal","Jyggalag","Shoggoth","Daedric Prince"))
                return Math.Min(currentTier, 0);
            if (ContainsAny(editorId, "DragonPriest","Lich","WraithLord","WraithKnight",
                                      "WraithArchwitch","NecroLich","AyleidLich","BoneLord") ||
                ContainsAny(name,     "Dragon Priest","Lich","Necromancer"))
                return Math.Min(currentTier, 3);
            if (ContainsAny(editorId, "VampireLord") || ContainsAny(name, "Vampire Lord"))
                return Math.Min(currentTier, 5);
            if (ContainsAny(editorId, "Vampire")     || ContainsAny(name, "Vampire"))
                return Math.Min(currentTier, 8);
            if (ContainsAny(editorId, "Zombie","Undead","Ghost","Wraith","Shade",
                                      "Draugr","Skeleton","Wight","Revenant","Banshee") ||
                ContainsAny(name,     "Zombie","Undead","Ghost","Wraith","Shade"))
                return Math.Min(currentTier, 9);
            if (ContainsAny(editorId, "Golem","Construct","Automaton","Centurion",
                                      "Dwemerbot","Droidmine") ||
                ContainsAny(name,     "Golem","Construct","Automaton","Centurion"))
                return Math.Min(currentTier, 6);
            return currentTier;
        }

        private static int ApplyNpcKeywordOverrides(INpcGetter npc, int currentTier, ILinkCache lc)
        {
            if (npc.Keywords?.Any(k =>
                    k.TryResolve(lc, out var kw) &&
                    kw.EditorID?.Equals("DLC1_IS_Vampire", StringComparison.OrdinalIgnoreCase) == true)
                == true)
                return Math.Min(currentTier, 5);
            if (npc.HasKeyword(Skyrim.Keyword.Vampire))
                return Math.Min(currentTier, 8);
            return currentTier;
        }

        // -------------------------------------------------------------------------
        // Level computation — single formula, three-level fallback
        //
        //   t = (sourceLvl - poolMin) / (poolMax - poolMin)
        //   newLevel = tMin + t * (tMax - tMin)
        //
        // Pool priority: faction → race → tier (always available)
        // When sourceLvl = 0: boss heuristic → top quarter; else → midpoint
        // -------------------------------------------------------------------------
        private static short ComputeLevel(
            NpcAssessment a,
            Dictionary<string, (int Min, int Max)> factionRanges,
            Dictionary<FormKey, (int Min, int Max)> raceRanges,
            Dictionary<int, (int Min, int Max)> tierRanges,
            Settings settings)
        {
            var (tMin, tMax) = TierSystem.GetRange(a.Tier, settings.TierScalingBase);

            // No authored level — heuristic placement only
            if (a.SourceLevel <= 0)
            {
                bool isBoss = settings.BossTokens.Any(t =>
                    a.EditorId.Contains(t, StringComparison.OrdinalIgnoreCase));
                int placed = isBoss
                    ? tMin + (tMax - tMin) * 3 / 4
                    : (tMin + tMax) / 2;
                return (short)Math.Clamp(placed + settings.GlobalOffset, 1, short.MaxValue);
            }

            // Resolve pool: faction → race → tier
            (int poolMin, int poolMax) pool;
            if (a.FactionKey is not null && factionRanges.TryGetValue(a.FactionKey, out var fr))
                pool = fr;
            else if (raceRanges.TryGetValue(a.RaceFormKey, out var rr))
                pool = rr;
            else if (tierRanges.TryGetValue(a.Tier, out var tr))
                pool = tr;
            else
                pool = (a.SourceLevel, a.SourceLevel); // solo NPC, no peers at all

            // Map vanilla percentile onto new range
            int span = Math.Max(pool.poolMax - pool.poolMin, 1);
            float t = Math.Clamp((float)(a.SourceLevel - pool.poolMin) / span, 0f, 1f);
            int result = (int)Math.Round(tMin + t * (tMax - tMin));

            result = Math.Clamp(result + settings.GlobalOffset, 1, short.MaxValue);
            if (settings.PrintDebugOutput)
                Console.WriteLine($"  {a.EditorId}: tier={a.Tier} [{tMin},{tMax}] src={a.SourceLevel} pool=[{pool.poolMin},{pool.poolMax}] t={t:F3} -> {result}");

            return (short)result;
        }

        public static void ApplyLevel(INpc npc, short newLevel)
        {
            npc.Configuration.Level = new NpcLevel() { Level = newLevel };
            npc.Configuration.CalcMinLevel = 1;
            npc.Configuration.CalcMaxLevel = newLevel;
        }

        // Distribute Health/Magicka/Stamina offsets from scratch using NPCStatsPerLevel * level,
        // proportioned by the class StatWeights — same pattern as RelevelNPCSkills for skills.
        // Overwrites whatever the original author put in, giving every NPC a clean stat budget
        // derived purely from their new level and class.
        public static bool RelevelNPCStats(Npc npc, ILinkCache linkCache)
        {
            if (Settings.NPCStatsPerLevel <= 0) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats) && !npc.Template.IsNull)
                return false;
            if (npc.Configuration.Level is not NpcLevel npcLevel) return false;
            if (!npc.Class.TryResolve(linkCache, out var cls)) return false;

            int totalPoints = (int)Math.Round(Settings.NPCStatsPerLevel * npcLevel.Level);
            float hW = cls.StatWeights[BasicStat.Health];
            float mW = cls.StatWeights[BasicStat.Magicka];
            float sW = cls.StatWeights[BasicStat.Stamina];
            float total = hW + mW + sW;

            // If all weights are zero fall back to equal distribution
            if (total <= 0) { hW = 1; mW = 1; sW = 1; total = 3; }

            npc.Configuration.HealthOffset  = (short)Math.Round(totalPoints * (hW / total));
            npc.Configuration.MagickaOffset = (short)Math.Round(totalPoints * (mW / total));
            npc.Configuration.StaminaOffset = (short)Math.Round(totalPoints * (sW / total));

            // Auto-calc stats overrides the offsets at runtime — clear it so our
            // computed values are actually used by the engine.
            npc.Configuration.Flags &= ~NpcConfiguration.Flag.AutoCalcStats;

            return true;
        }

        // -------------------------------------------------------------------------
        // Civilian detection — unchanged
        // -------------------------------------------------------------------------
        private static bool IsCivilian(INpcGetter npc, ILinkCache lc)
        {
            if (!npc.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Unique)) return false;
            if (!npc.Race.TryResolve(lc, out var race)) return false;
            if (!race.HasKeyword(Skyrim.Keyword.ActorTypeNPC)) return false;

            if (npc.Class.TryResolve(lc, out var cls))
            {
                string clsId   = cls.EditorID ?? "";
                string clsName = cls.Name?.String ?? "";
                if (CivilianClassTerms.Any(t =>
                    clsId.Contains(t, StringComparison.OrdinalIgnoreCase) ||
                    clsName.Contains(t, StringComparison.OrdinalIgnoreCase)))
                    return true;
            }
            return false;
        }

        // -------------------------------------------------------------------------
        // Skill redistribution — unchanged
        // -------------------------------------------------------------------------
        private static void DistributeSkills(
            IReadOnlyDictionary<Skill, byte> skillWeights,
            IDictionary<Skill, byte> skillValues,
            int skillPoints)
        {
            float weightSum;
            bool firstPass = true;
            byte maxSkill = Settings.NPCMaxSkillLevel;
            var tempWeights = skillWeights.ToList();
            do
            {
                int overflow = 0;
                weightSum = tempWeights.Any() ? tempWeights.Sum(x => x.Value) : 0;
                for (int i = tempWeights.Count - 1; i >= 0; --i)
                {
                    if (firstPass) skillValues[tempWeights[i].Key] = 15;
                    int addedPoints = (int)Math.Round(skillPoints * (tempWeights[i].Value / weightSum));
                    int newVal = skillValues[tempWeights[i].Key] + addedPoints;
                    skillValues[tempWeights[i].Key] = (byte)Math.Min(newVal, byte.MaxValue);
                    if (skillValues[tempWeights[i].Key] > maxSkill)
                    {
                        overflow += skillValues[tempWeights[i].Key] - maxSkill;
                        skillValues[tempWeights[i].Key] = maxSkill;
                        tempWeights.RemoveAt(i);
                    }
                }
                firstPass = false;
                skillPoints = overflow;
            } while (skillPoints > 0 && weightSum > 0);
        }

        private static bool RelevelNPCSkills(Npc npc, ILinkCache linkCache)
        {
            if (Settings.NPCSkillsPerLevel <= 0) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats) && !npc.Template.IsNull)
                return false;
            if (npc.Configuration.Level is not NpcLevel npcLevel) return false;
            if (!npc.Class.TryResolve(linkCache, out var classGetter)) return false;
            // Only redistribute skills for humanoids — writing DNAM skill values to
            // creatures breaks their AI detection (Skyrim reads those for perception).
            if (!npc.Race.TryResolve(linkCache, out var race)) return false;
            if (!race.HasKeyword(Skyrim.Keyword.ActorTypeNPC) && !race.HasKeyword(Skyrim.Keyword.ActorTypeUndead)) return false;

            if (npc.PlayerSkills is null)
                npc.PlayerSkills = new PlayerSkills();

            DistributeSkills(classGetter.SkillWeights, npc.PlayerSkills.SkillValues,
                (int)Math.Round(Settings.NPCSkillsPerLevel * npcLevel.Level));
            return true;
        }

        // -------------------------------------------------------------------------
        // Class rebuild — unchanged
        // -------------------------------------------------------------------------
        private static void GetItemSkillWeights(IItemGetter item, IDictionary<Skill, float> w, float div = 1)
        {
            if (item is IWeaponGetter wpn && wpn.Data?.Skill is { } sk)
                w[(Skill)sk] += 1 / div;
            else if (item is IArmorGetter arm)
            {
                if (arm.HasKeyword(Skyrim.Keyword.ArmorShield))     w[Skill.Block]      += 1 / div;
                if (arm.HasKeyword(Skyrim.Keyword.ArmorHeavy))      w[Skill.HeavyArmor] += 1 / div;
                else if (arm.HasKeyword(Skyrim.Keyword.ArmorLight)) w[Skill.LightArmor] += 1 / div;
            }
        }

        private static void GetLvliSkillWeights(ILeveledItemGetter lvli, IDictionary<Skill, float> w,
            ILinkCache lc, float div = 1)
        {
            var nodes = lvli.Entries?.ToList() ?? new();
            while (nodes.Any())
            {
                var n = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (n.Data is null || !n.Data.Reference.TryResolve(lc, out var entry)) continue;
                if (entry is ILeveledItemGetter sub)
                    foreach (var c in sub.Entries.EmptyIfNull()) nodes.Add(c);
                else GetItemSkillWeights(entry, w, div);
            }
        }

        private static void GetSpellSkillWeights(ISpellRecordGetter spell, IDictionary<Skill, float> w,
            ILinkCache lc, float div = 1)
        {
            if (spell is not ISpellGetter sg || sg.Type != SpellType.Spell) return;
            foreach (var eff in sg.Effects)
            {
                if (!eff.BaseEffect.TryResolve(lc, out var mgef)) continue;
                var addTo = mgef.MagicSkill switch
                {
                    ActorValue.Destruction  => (Skill?)Skill.Destruction,
                    ActorValue.Alteration   => Skill.Alteration,
                    ActorValue.Conjuration  => Skill.Conjuration,
                    ActorValue.Illusion     => Skill.Illusion,
                    ActorValue.Restoration  => Skill.Restoration,
                    _ => null
                };
                if (addTo is { } s) { w[s] += 1 / div; return; }
            }
        }

        private static void GetLvlSpellWeights(ILeveledSpellGetter lvls, IDictionary<Skill, float> w,
            ILinkCache lc, float div = 1)
        {
            var nodes = lvls.Entries?.ToList() ?? new();
            while (nodes.Any())
            {
                var n = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (n.Data is null || !n.Data.Reference.TryResolve(lc, out var entry)) continue;
                if (entry is ILeveledSpellGetter sub)
                    foreach (var c in sub.Entries.EmptyIfNull()) nodes.Add(c);
                else GetSpellSkillWeights(entry, w, lc, div);
            }
        }

        private static void PopulateByInventory(INpcSpawnGetter spawn, IDictionary<Skill, float> w, ILinkCache lc)
        {
            var nodes = new List<(INpcSpawnGetter, int)>();
            if (spawn is INpcGetter ng)
            {
                if (ng.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Inventory)
                    && ng.Template.TryResolve(lc, out var t)) nodes.Add((t, 1));
                else foreach (var e in ng.Items.EmptyIfNull())
                    if (e.Item.Item.TryResolve(lc, out var it))
                    { if (it is ILeveledItemGetter li) GetLvliSkillWeights(li, w, lc); else GetItemSkillWeights(it, w); }
            }
            else if (spawn is ILeveledNpcGetter ln)
                foreach (var e in ln.Entries.EmptyIfNull())
                    if (e.Data?.Reference.TryResolve(lc, out var s) == true) nodes.Add((s, ln.Entries!.Count));

            while (nodes.Any())
            {
                var (node, div) = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (node is ILeveledNpcGetter l2)
                    foreach (var c in l2.Entries.EmptyIfNull())
                        if (c.Data?.Reference.TryResolve(lc, out var cs) == true) nodes.Add((cs, l2.Entries!.Count));
                else if (node is INpcGetter sg2)
                {
                    if (sg2.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Inventory)
                        && sg2.Template.TryResolve(lc, out var t2)) nodes.Add((t2, 1));
                    else foreach (var e in sg2.Items.EmptyIfNull())
                        if (e.Item.Item.TryResolve(lc, out var it))
                        { if (it is ILeveledItemGetter li) GetLvliSkillWeights(li, w, lc, div); else GetItemSkillWeights(it, w, div); }
                }
            }
        }

        private static void PopulateBySpells(INpcSpawnGetter spawn, IDictionary<Skill, float> w, ILinkCache lc)
        {
            var nodes = new List<(INpcSpawnGetter, int)>();
            if (spawn is INpcGetter ng)
            {
                if (ng.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.SpellList)
                    && ng.Template.TryResolve(lc, out var t)) nodes.Add((t, 1));
                else foreach (var sp in ng.ActorEffect.EmptyIfNull())
                    if (sp.TryResolve(lc, out var sr))
                    { if (sr is ILeveledSpellGetter ls) GetLvlSpellWeights(ls, w, lc); else GetSpellSkillWeights(sr, w, lc); }
            }
            else if (spawn is ILeveledNpcGetter ln)
                foreach (var e in ln.Entries.EmptyIfNull())
                    if (e.Data?.Reference.TryResolve(lc, out var s) == true) nodes.Add((s, ln.Entries!.Count));

            while (nodes.Any())
            {
                var (node, div) = nodes[^1]; nodes.RemoveAt(nodes.Count - 1);
                if (node is ILeveledNpcGetter l2)
                    foreach (var c in l2.Entries.EmptyIfNull())
                        if (c.Data?.Reference.TryResolve(lc, out var cs) == true) nodes.Add((cs, l2.Entries!.Count));
                else if (node is INpcGetter sg2)
                {
                    if (sg2.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.SpellList)
                        && sg2.Template.TryResolve(lc, out var t2)) nodes.Add((t2, 1));
                    else foreach (var sp in sg2.ActorEffect.EmptyIfNull())
                        if (sp.TryResolve(lc, out var sr))
                        { if (sr is ILeveledSpellGetter ls) GetLvlSpellWeights(ls, w, lc, div); else GetSpellSkillWeights(sr, w, lc, div); }
                }
            }
        }

        private static void PopulateByOutfit(Npc npc, IDictionary<Skill, float> w, ILinkCache lc)
        {
            if (npc.DefaultOutfit.IsNull || !npc.DefaultOutfit.TryResolve(lc, out var outfit)) return;
            foreach (var entry in outfit!.Items.EmptyIfNull())
                if (entry.TryResolve(lc, out var eg))
                {
                    if (eg is ILeveledItemGetter li) GetLvliSkillWeights(li, w, lc);
                    else if (eg is IArmorGetter arm)
                    {
                        if (arm.HasKeyword(Skyrim.Keyword.ArmorShield))     w[Skill.Block]      += 1;
                        if (arm.HasKeyword(Skyrim.Keyword.ArmorHeavy))      w[Skill.HeavyArmor] += 1;
                        else if (arm.HasKeyword(Skyrim.Keyword.ArmorLight)) w[Skill.LightArmor] += 1;
                    }
                }
        }

        private static void CalculateClassWeights(Class cls, IDictionary<Skill, float> w)
        {
            var list = w.Where(e => e.Value > 0).ToList();
            list.Sort((x, y) => x.Value.CompareTo(y.Value));
            float last = list[0].Value;
            for (int rank = 1, i = 0; i < list.Count; i++)
            {
                if (list[i].Value > last) { rank = i + 1; last = list[i].Value; }
                list[i] = new(list[i].Key, rank);
            }
            bool isHybrid =
                list.Any(x => x.Key is Skill.Block or Skill.OneHanded or Skill.TwoHanded or Skill.LightArmor or Skill.HeavyArmor) &&
                list.Any(x => x.Key is Skill.Illusion or Skill.Alteration or Skill.Conjuration or Skill.Destruction or Skill.Restoration);
            if (isHybrid)
            {
                float total = cls.StatWeights.Sum(x => x.Value);
                float combatSum = cls.StatWeights[BasicStat.Health] > cls.StatWeights[BasicStat.Magicka]
                    ? cls.StatWeights[BasicStat.Health] + cls.StatWeights[BasicStat.Stamina]
                    : cls.StatWeights[BasicStat.Magicka] + cls.StatWeights[BasicStat.Stamina];
                float magicSum = cls.StatWeights[BasicStat.Magicka] > cls.StatWeights[BasicStat.Health]
                    ? cls.StatWeights[BasicStat.Magicka] + cls.StatWeights[BasicStat.Stamina]
                    : cls.StatWeights[BasicStat.Health] + cls.StatWeights[BasicStat.Stamina];
                if (cls.StatWeights[BasicStat.Health] == cls.StatWeights[BasicStat.Magicka])
                    total -= cls.StatWeights[BasicStat.Stamina];
                float cr = combatSum / total, mr = magicSum / total;
                for (int i = 0; i < list.Count; i++)
                    list[i] = list[i].Key switch
                    {
                        Skill.Block or Skill.OneHanded or Skill.TwoHanded or Skill.LightArmor or Skill.HeavyArmor
                            => new(list[i].Key, (float)Math.Round(list[i].Value * cr)),
                        Skill.Illusion or Skill.Alteration or Skill.Conjuration or Skill.Destruction or Skill.Restoration
                            => new(list[i].Key, (float)Math.Round(list[i].Value * mr)),
                        _ => list[i]
                    };
            }
            list.ForEach(x => w[x.Key] = x.Value);
            if (!isHybrid && w[Skill.Block] == 0 && (w[Skill.OneHanded] > 0 || w[Skill.TwoHanded] > 0))
                w[Skill.Block] = 1;
        }

        private static bool RebalanceClassValues(Npc npc, IPatcherState<ISkyrimMod, ISkyrimModGetter> state, ILinkCache lc)
        {
            if (!Settings.RebuildNPCClasses) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats) && !npc.Template.IsNull) return false;
            if (!npc.Race.TryResolve<IRaceGetter>(lc, out var race)) return false;
            if (!npc.Class.TryResolve(lc, out var cls)) return false;
            if (npc.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Unique)
                && ExcludedClasses.Any(e => (cls.EditorID?.Contains(e, StringComparison.OrdinalIgnoreCase) ?? false)
                                         || (cls.Name?.String?.Contains(e, StringComparison.OrdinalIgnoreCase) ?? false)))
                return false;

            IDictionary<Skill, float> w = new Dictionary<Skill, float>();
            cls.SkillWeights.ForEach(x => w[x.Key] = 0);
            PopulateByInventory(npc, w, lc);
            PopulateBySpells(npc, w, lc);
            PopulateByOutfit(npc, w, lc);
            w.ForEach(x => w[x.Key] = (float)Math.Ceiling(x.Value));
            if (w.All(x => x.Value == 0)) return false;

            bool isHumanoid = race.HasKeyword(Skyrim.Keyword.ActorTypeNPC)
                           || race.HasKeyword(Skyrim.Keyword.ActorTypeUndead);

            if (isHumanoid)
            {
                // Humanoids: create a fresh per-NPC class record so we don't pollute
                // a shared class that other NPCs reference.
                var newClass = state.PatchMod.Classes.AddNew();
                newClass.EditorID = "SRClass" + npc.EditorID;
                if (cls.Name is not null) newClass.Name = cls.Name.DeepCopy();
                newClass.StatWeights[BasicStat.Health]  = cls.StatWeights[BasicStat.Health];
                newClass.StatWeights[BasicStat.Magicka] = cls.StatWeights[BasicStat.Magicka];
                newClass.StatWeights[BasicStat.Stamina] = cls.StatWeights[BasicStat.Stamina];
                foreach (var sw in cls.SkillWeights)
                    newClass.SkillWeights[sw.Key] = sw.Value;
                npc.Class = newClass.ToLink();
                CalculateClassWeights(newClass, w);
                newClass.SkillWeights.ForEach(x => newClass.SkillWeights[x.Key] = 0);
                w.ForEach(x => newClass.SkillWeights[x.Key] = (byte)x.Value);
            }
            else
            {
                // Creatures: patch the existing class record in-place so the NPC's
                // class reference never changes (avoids invisible/unselectable actors).
                var classOverride = state.PatchMod.Classes.GetOrAddAsOverride(cls);
                CalculateClassWeights(classOverride, w);
                classOverride.SkillWeights.ForEach(x => classOverride.SkillWeights[x.Key] = 0);
                w.ForEach(x => classOverride.SkillWeights[x.Key] = (byte)x.Value);
            }

            return true;
        }

        // -------------------------------------------------------------------------
        // Perk distribution — unchanged
        // -------------------------------------------------------------------------
        private static bool GetTreeFromSkill(Skill s, ILinkCache lc, out IActorValueInformationGetter? av)
        {
            av = s switch
            {
                Skill.Alchemy     => Skyrim.ActorValueInformation.AVAlchemy.TryResolve(lc),
                Skill.Alteration  => Skyrim.ActorValueInformation.AVAlteration.TryResolve(lc),
                Skill.Archery     => Skyrim.ActorValueInformation.AVMarksman.TryResolve(lc),
                Skill.Block       => Skyrim.ActorValueInformation.AVBlock.TryResolve(lc),
                Skill.Conjuration => Skyrim.ActorValueInformation.AVConjuration.TryResolve(lc),
                Skill.Destruction => Skyrim.ActorValueInformation.AVDestruction.TryResolve(lc),
                Skill.Enchanting  => Skyrim.ActorValueInformation.AVEnchanting.TryResolve(lc),
                Skill.HeavyArmor  => Skyrim.ActorValueInformation.AVHeavyArmor.TryResolve(lc),
                Skill.Illusion    => Skyrim.ActorValueInformation.AVMysticism.TryResolve(lc),
                Skill.LightArmor  => Skyrim.ActorValueInformation.AVLightArmor.TryResolve(lc),
                Skill.Lockpicking => Skyrim.ActorValueInformation.AVLockpicking.TryResolve(lc),
                Skill.OneHanded   => Skyrim.ActorValueInformation.AVOneHanded.TryResolve(lc),
                Skill.Pickpocket  => Skyrim.ActorValueInformation.AVPickpocket.TryResolve(lc),
                Skill.Restoration => Skyrim.ActorValueInformation.AVRestoration.TryResolve(lc),
                Skill.Smithing    => Skyrim.ActorValueInformation.AVSmithing.TryResolve(lc),
                Skill.Sneak       => Skyrim.ActorValueInformation.AVSneak.TryResolve(lc),
                Skill.Speech      => Skyrim.ActorValueInformation.AVSpeechcraft.TryResolve(lc),
                Skill.TwoHanded   => Skyrim.ActorValueInformation.AVTwoHanded.TryResolve(lc),
                _ => null
            };
            return av is not null;
        }

        private static bool PerformCompare<T>(IConditionGetter? c, T l, T r) where T : IComparable<T>
            => c?.CompareOperator switch
            {
                CompareOperator.EqualTo              => l.CompareTo(r) == 0,
                CompareOperator.GreaterThan          => l.CompareTo(r) > 0,
                CompareOperator.GreaterThanOrEqualTo => l.CompareTo(r) >= 0,
                CompareOperator.LessThan             => l.CompareTo(r) < 0,
                CompareOperator.LessThanOrEqualTo    => l.CompareTo(r) <= 0,
                CompareOperator.NotEqualTo           => l.CompareTo(r) != 0,
                _ => false
            };

        private static void RemoveVanillaPerks(Npc npc, ILinkCache vanillaCache)
        {
            if (npc.Perks is null || npc.Perks.Count == 0) return;
            for (int i = npc.Perks.Count - 1; i >= 0; --i)
            {
                if (npc.Perks[i].Perk.Equals(Skyrim.Perk.AlchemySkillBoosts) ||
                    npc.Perks[i].Perk.Equals(Skyrim.Perk.PerkSkillBoosts)) continue;
                if (vanillaCache.TryResolve<IPerkGetter>(npc.Perks[i].Perk, out _))
                    npc.Perks.RemoveAt(i);
            }
        }

        private static bool FulfillsPerkConditions(Npc npc, IPerkGetter perk, Skill skill, ILinkCache lc)
        {
            if (npc.Perks!.Any(x => x.Perk.Equals(perk.ToLink()))) return false;
            foreach (var cond in perk.Conditions)
            {
                if (cond is not ConditionFloat cf) continue;
                if (cf.Data is GetBaseActorValueConditionData avd && (int)avd.ActorValue == (int)skill)
                { if (!PerformCompare(cf, npc.PlayerSkills!.SkillValues[skill], cf.ComparisonValue)) return false; }
                else if (cf.Data is HasPerkConditionData pd && pd.Perk.Link.TryResolve(lc, out var req))
                {
                    bool has = npc.Perks!.Any(x => x.Perk.Equals(req.ToLink()));
                    if ((cf.CompareOperator == CompareOperator.EqualTo    && cf.ComparisonValue == 1 && !has) ||
                        (cf.CompareOperator == CompareOperator.NotEqualTo && cf.ComparisonValue == 1 && has)  ||
                        (cf.CompareOperator == CompareOperator.EqualTo    && cf.ComparisonValue == 0 && has)  ||
                        (cf.CompareOperator == CompareOperator.NotEqualTo && cf.ComparisonValue == 0 && !has))
                        return false;
                }
            }
            return true;
        }

        private static bool DistributeNPCPerks(Npc npc, ILinkCache lc, ILinkCache vanillaCache,
            ExcludedList excludedPerks)
        {
            if (Settings.NPCPerksPerLevel <= 0) return false;
            if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.SpellList) && !npc.Template.IsNull) return false;
            if (!npc.Class.TryResolve<IClassGetter>(lc, out var cls)) return false;
            if (!npc.Race.TryResolve<IRaceGetter>(lc, out var race)) return false;
            if (!race.HasKeyword(Skyrim.Keyword.ActorTypeNPC) && !race.HasKeyword(Skyrim.Keyword.ActorTypeUndead)) return false;
            foreach (var kw in Settings.PerkDistributionFilter)
                if (npc.HasKeyword(kw) || race.HasKeyword(kw)) return false;

            if (npc.PlayerSkills is null)
                npc.PlayerSkills = new PlayerSkills();

            float perksTotal = Settings.NPCPerksPerLevel;
            if (npc.Configuration.Level is NpcLevel nl)
                perksTotal *= nl.Level;
            else if (npc.Configuration.Level is PcLevelMult)
            {
                if (Settings.FollowerPerkLevel <= 0) return false;
                perksTotal *= Settings.FollowerPerkLevel;
            }

            npc.Perks ??= new();
            if (Settings.RemoveVanillaPerks) RemoveVanillaPerks(npc, vanillaCache);

            int overflow = 0;
            var perkDist = cls.SkillWeights.ToList();
            float wSum = perkDist.Any() ? perkDist.Sum(x => x.Value) : 0;

            foreach (var pw in perkDist)
            {
                if (pw.Value <= 0) continue;
                int toSpend = (int)Math.Round(overflow + perksTotal * (pw.Value / wSum));
                if (toSpend <= 0) continue;
                if (!GetTreeFromSkill(pw.Key, lc, out var tree) || tree!.PerkTree is null) continue;

                while (toSpend > 0)
                {
                    bool added = false;
                    foreach (var node in tree.PerkTree)
                    {
                        if (toSpend <= 0) break;
                        if (!node.Perk.TryResolve(lc, out var perkEntry) || perkEntry.EditorID is null) continue;
                        if (excludedPerks.Keys.Any(k => perkEntry.EditorID.Contains(k, StringComparison.OrdinalIgnoreCase)) &&
                            !excludedPerks.ForbiddenKeys.Any(k => perkEntry.EditorID.Contains(k, StringComparison.OrdinalIgnoreCase))) continue;
                        if (FulfillsPerkConditions(npc, perkEntry, pw.Key, lc))
                        {
                            --toSpend; added = true;
                            npc.Perks!.Add(new PerkPlacement { Perk = perkEntry.ToLink(), Rank = 1 });
                        }
                        while (toSpend > 0 && perkEntry.NextPerk.TryResolve<IPerkGetter>(lc, out perkEntry))
                        {
                            if (FulfillsPerkConditions(npc, perkEntry, pw.Key, lc))
                            { --toSpend; added = true; npc.Perks!.Add(new PerkPlacement { Perk = perkEntry.ToLink(), Rank = 1 }); }
                            else break;
                        }
                    }
                    if (!added) { overflow = toSpend; break; }
                    else overflow = 0;
                }
            }
            if (npc.Perks.Count == 0) npc.Perks = null;
            return true;
        }

        private static void DisableExtraDamagePerks(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (!Settings.DisableExtraDamagePerks) return;
            foreach (var perkGetter in state.LoadOrder.PriorityOrder.Perk().WinningOverrides()
                .Where(x => x.EditorID?.Contains("crExtraDamage", StringComparison.OrdinalIgnoreCase) == true))
            {
                var perk = state.PatchMod.Perks.GetOrAddAsOverride(perkGetter);
                perk.Effects.Clear();
            }
        }

        // -------------------------------------------------------------------------
        // RunPatch
        // -------------------------------------------------------------------------
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            if (state.ExtraSettingsDataPath is null)
            { Console.Error.WriteLine("ERROR: ExtraSettingsDataPath is null."); return; }

            // Seed default data files on first run (or if missing / force-reseeded)
            Directory.CreateDirectory(state.ExtraSettingsDataPath);
            string builtDataPath = Path.Combine(AppContext.BaseDirectory, "Data");
            string seedSource = Directory.Exists(builtDataPath) ? builtDataPath
                : state.InternalDataPath ?? "";
            if (!string.IsNullOrEmpty(seedSource) && Directory.Exists(seedSource))
            {
                foreach (var src in Directory.EnumerateFiles(seedSource, "*.json", SearchOption.TopDirectoryOnly))
                {
                    string dest = Path.Combine(state.ExtraSettingsDataPath, Path.GetFileName(src));
                    if (!File.Exists(dest) || Settings.ForceReseedData)
                    {
                        File.Copy(src, dest, overwrite: true);
                        Console.WriteLine($"  {(Settings.ForceReseedData ? "Force-reseeded" : "Seeded")} data file: {Path.GetFileName(src)}");
                    }
                }
            }

            Console.WriteLine("=== Skyrim Releveler — Loading Data ===");

            // Named NPC overrides
            var namedPath = Path.Combine(state.ExtraSettingsDataPath, "named_npcs.json");
            if (!File.Exists(namedPath)) { Console.Error.WriteLine($"ERROR: Missing {namedPath}"); return; }
            var namedNpcs = JsonConvert.DeserializeObject<Dictionary<string, int>>(
                File.ReadAllText(namedPath),
                new JsonSerializerSettings { Error = (s, a) => a.ErrorContext.Handled = true }) ?? new();
            Console.WriteLine($"  Named NPC overrides : {namedNpcs.Count}");

            // Custom followers
            var followersPath = Path.Combine(state.ExtraSettingsDataPath, "customFollowers.json");
            var customFollowers = File.Exists(followersPath)
                ? JsonConvert.DeserializeObject<FollowerList>(File.ReadAllText(followersPath)) ?? new()
                : new FollowerList();

            // Excluded NPCs
            var exclNpcsPath = Path.Combine(state.ExtraSettingsDataPath, "excludedNPCs.json");
            var excludedNPCs = File.Exists(exclNpcsPath)
                ? JsonConvert.DeserializeObject<ExcludedList>(File.ReadAllText(exclNpcsPath)) ?? new()
                : new ExcludedList();

            // Excluded perks
            var exclPerksPath = Path.Combine(state.ExtraSettingsDataPath, "excludedPerks.json");
            var excludedPerks = File.Exists(exclPerksPath)
                ? JsonConvert.DeserializeObject<ExcludedList>(File.ReadAllText(exclPerksPath)) ?? new()
                : new ExcludedList();

            ILinkCache? vanillaCache = null;
            ILinkCache GetVanillaCache() => vanillaCache ??= LoadOrder.Import<ISkyrimModGetter>(
                state.DataFolderPath,
                new List<ModKey> { Skyrim.ModKey, Dawnguard.ModKey, Dragonborn.ModKey },
                GameRelease.SkyrimSE).ToImmutableLinkCache();

            var linkCache = state.LoadOrder.PriorityOrder.ToImmutableLinkCache();

            if (Settings.DumpRaces || Settings.PrintDebugOutput)
            {
                Console.WriteLine("=== RACE DUMP ===");
                foreach (var race in state.LoadOrder.PriorityOrder.Race().WinningOverrides())
                    Console.WriteLine($"  {race.EditorID ?? "(null)"}");
                Console.WriteLine("=== END RACE DUMP ===");
            }

            // -----------------------------------------------------------------------
            // Helper closures
            // -----------------------------------------------------------------------
            static List<string> SplitTokens(string s)
            {
                var tokens = new List<string>(); int start = 0;
                for (int i = 1; i <= s.Length; i++)
                {
                    bool b = i == s.Length
                        || (char.IsUpper(s[i]) && i > 0 && char.IsLower(s[i-1]))
                        || (char.IsUpper(s[i]) && i+1 < s.Length && char.IsLower(s[i+1]) && char.IsUpper(s[i-1]))
                        || (char.IsDigit(s[i]) != char.IsDigit(s[i-1]));
                    if (b) { var t = s.Substring(start, i - start); if (t.Length > 0) tokens.Add(t); start = i; }
                }
                return tokens;
            }

            int? FindNamedLevel(string? editorId)
            {
                if (string.IsNullOrEmpty(editorId)) return null;
                var et = SplitTokens(editorId);
                foreach (var (key, level) in namedNpcs)
                {
                    var kt = SplitTokens(key);
                    if (kt.Count == 0) continue;
                    for (int i = 0; i <= et.Count - kt.Count; i++)
                    {
                        bool match = true;
                        for (int j = 0; j < kt.Count; j++)
                            if (!string.Equals(et[i+j], kt[j], StringComparison.OrdinalIgnoreCase)) { match = false; break; }
                        if (match) return level;
                    }
                }
                return null;
            }

            bool IsExcluded(string editorId) =>
                excludedNPCs.Keys.Any(k => editorId.Contains(k, StringComparison.OrdinalIgnoreCase)) &&
                !excludedNPCs.ForbiddenKeys.Any(k => editorId.Contains(k, StringComparison.OrdinalIgnoreCase));

            bool IsFollower(INpcGetter npc)
            {
                if (!Settings.ScaleFollowers || npc.EditorID is null) return false;
                if (npc.Factions.Any(f => f.Faction.Equals(Skyrim.Faction.PotentialFollowerFaction) ||
                                          f.Faction.Equals(Skyrim.Faction.PotentialHireling))) return true;
                foreach (var rankEntry in npc.Factions)
                {
                    if (!rankEntry.Faction.TryResolve(linkCache, out var fac) || fac.EditorID is null) continue;
                    if (fac.EditorID.Contains("follower", StringComparison.OrdinalIgnoreCase)) return true;
                }
                if (npc.Configuration.Level is IPcLevelMultGetter &&
                    npc.Configuration.CalcMaxLevel <= 0 &&
                    npc.Configuration.CalcMinLevel <= 0)
                    return true;
                foreach (var entry in customFollowers.Followers)
                {
                    if (string.IsNullOrEmpty(entry.Key)) continue;
                    if (!npc.EditorID.Contains(entry.Key, StringComparison.OrdinalIgnoreCase)) continue;
                    if (entry.ForbiddenKeys.Any(fk => npc.EditorID.Contains(fk, StringComparison.OrdinalIgnoreCase))) continue;
                    return true;
                }
                return false;
            }

            static bool IsNonHostileFaction(string facId) =>
                facId.Contains("Follower",  StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Vendor",    StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Player",    StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Crime",     StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Merchant",  StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Hireling",  StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Potential", StringComparison.OrdinalIgnoreCase) ||
                facId.Contains("Steward",   StringComparison.OrdinalIgnoreCase) ||
                facId.Equals("CreatureFaction",  StringComparison.OrdinalIgnoreCase) ||
                facId.Equals("AnimalFaction",    StringComparison.OrdinalIgnoreCase) ||
                facId.Equals("PreyFaction",      StringComparison.OrdinalIgnoreCase) ||
                facId.Equals("PredatorFaction",  StringComparison.OrdinalIgnoreCase) ||
                facId.Equals("WildlifeFaction",  StringComparison.OrdinalIgnoreCase) ||
                (facId.StartsWith("Creature", StringComparison.OrdinalIgnoreCase) && facId.Length < 20);

            bool ShouldSkip(INpcGetter g, string edId)
            {
                if (NpcsToIgnore.Contains(g)) return true;
                if (g.Configuration.Flags.HasFlag(NpcConfiguration.Flag.IsCharGenFacePreset)) return true;
                if (g.HasKeyword(Skyrim.Keyword.PlayerKeyword)) return true;
                if (IsExcluded(edId)) return true;
                if (IsFollower(g)) return true;
                if (FindNamedLevel(edId) is not null) return true;
                if (IsCivilian(g, linkCache)) return true;
                return false;
            }

            // -----------------------------------------------------------------------
            // Pre-pass: build faction member counts, then assessments + peer ranges
            // -----------------------------------------------------------------------

            if (!Settings.EnableReleveling)
                Console.WriteLine("  Releveling is DISABLED — NPC levels will not be modified.");

            // Pass A — faction membership counts
            var factionMemberCount = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            foreach (var getter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                if (getter.EditorID is not { } edId0) continue;
                if (ShouldSkip(getter, edId0)) continue;
                foreach (var rankEntry in getter.Factions)
                {
                    if (!rankEntry.Faction.TryResolve(linkCache, out var fac) || fac.EditorID is null) continue;
                    if (IsNonHostileFaction(fac.EditorID)) continue;
                    factionMemberCount[fac.EditorID] = factionMemberCount.TryGetValue(fac.EditorID, out var cnt)
                        ? cnt + 1 : 1;
                }
            }

            // Pass B — build assessments and collect source levels per peer group
            var assessments = new Dictionary<FormKey, NpcAssessment>();
            var factionSourceLevels = new Dictionary<string, List<int>>(StringComparer.OrdinalIgnoreCase);
            var raceSourceLevels    = new Dictionary<FormKey, List<int>>();
            var tierSourceLevels    = new Dictionary<int, List<int>>();

            foreach (var getter in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                if (getter.EditorID is not { } edId) continue;
                if (ShouldSkip(getter, edId)) continue;

                int sourceLvl = GetSourceLevel(getter);
                int tier      = ClassifyNpc(getter, linkCache);

                // Pick the largest hostile faction
                string? bestFaction = null;
                int bestCount = 0;
                foreach (var rankEntry in getter.Factions)
                {
                    if (!rankEntry.Faction.TryResolve(linkCache, out var fac) || fac.EditorID is null) continue;
                    if (IsNonHostileFaction(fac.EditorID)) continue;
                    int cnt = factionMemberCount.TryGetValue(fac.EditorID, out var c) ? c : 0;
                    if (cnt > bestCount) { bestCount = cnt; bestFaction = fac.EditorID; }
                }

                // Only use a faction if it meets the minimum peer count
                if (bestCount < Settings.FactionMinPeers) bestFaction = null;

                var assessment = new NpcAssessment
                {
                    FormKey     = getter.FormKey,
                    EditorId    = edId,
                    Tier        = tier,
                    SourceLevel = sourceLvl,
                    FactionKey  = bestFaction,
                    RaceFormKey = getter.Race.FormKey,
                    ModKey      = getter.FormKey.ModKey,
                };
                assessments[getter.FormKey] = assessment;

                // Accumulate source levels for peer range computation
                if (sourceLvl > 0)
                {
                    if (bestFaction is not null)
                    {
                        if (!factionSourceLevels.TryGetValue(bestFaction, out var fl))
                            factionSourceLevels[bestFaction] = fl = new List<int>();
                        fl.Add(sourceLvl);
                    }

                    var raceKey = getter.Race.FormKey;
                    if (!raceSourceLevels.TryGetValue(raceKey, out var rl))
                        raceSourceLevels[raceKey] = rl = new List<int>();
                    rl.Add(sourceLvl);

                    if (!tierSourceLevels.TryGetValue(tier, out var tl))
                        tierSourceLevels[tier] = tl = new List<int>();
                    tl.Add(sourceLvl);
                }
            }

            // Build min/max ranges from collected source levels
            static (int Min, int Max) ToRange(List<int> levels)
            {
                int mn = levels[0], mx = levels[0];
                foreach (var v in levels) { if (v < mn) mn = v; if (v > mx) mx = v; }
                return (mn, mx);
            }

            var factionRanges = new Dictionary<string, (int Min, int Max)>(StringComparer.OrdinalIgnoreCase);
            foreach (var (k, v) in factionSourceLevels) factionRanges[k] = ToRange(v);

            var raceRanges = new Dictionary<FormKey, (int Min, int Max)>();
            foreach (var (k, v) in raceSourceLevels) raceRanges[k] = ToRange(v);

            var tierRanges = new Dictionary<int, (int Min, int Max)>();
            foreach (var (k, v) in tierSourceLevels) tierRanges[k] = ToRange(v);

            Console.WriteLine($"  Data loaded. Starting patch...");
            Console.WriteLine($"  NPCs assessed        : {assessments.Count}");
            Console.WriteLine($"  Factions with ranges : {factionRanges.Count}");
            Console.WriteLine($"  Races with ranges    : {raceRanges.Count}");
            Console.WriteLine($"  Tiers covered        : {tierRanges.Count}");
            Console.WriteLine();

            // -----------------------------------------------------------------------
            // Main pass
            // -----------------------------------------------------------------------
            int followersScaled = 0, namedCount = 0, civiliansScaled = 0,
                pipelineCount = 0, npcsProcessed = 0;

            foreach (var ctx in state.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
            {
                var getter = ctx.Record;
                if (NpcsToIgnore.Contains(getter)) continue;
                if (getter.EditorID is not { } editorId) continue;
                if (getter.Configuration.Flags.HasFlag(NpcConfiguration.Flag.IsCharGenFacePreset) ||
                    getter.HasKeyword(Skyrim.Keyword.PlayerKeyword)) continue;
                if (IsExcluded(editorId)) continue;

                // Use DeepCopy as a scratch object for all logic — nothing gets Set()
                // from this copy directly. Only the specific fields we touch are
                // transferred onto a proper context override at the end.
                Npc scratch = getter.DeepCopy();
                bool wasChanged = false;

                if (Settings.EnableReleveling)
                {
                    // Priority 1: followers
                    if (IsFollower(getter))
                    {
                        scratch.Configuration.Level = new PcLevelMult { LevelMult = 1f };
                        scratch.Configuration.CalcMinLevel = Math.Max(scratch.Configuration.CalcMinLevel, (short)1);
                        scratch.Configuration.CalcMaxLevel = short.MaxValue;
                        wasChanged = true;
                        ++followersScaled;
                        if (Settings.PrintDebugOutput) Console.WriteLine($"  {editorId}: follower -> unlimited scaling");
                    }
                    // Priority 2: named overrides
                    else if (FindNamedLevel(editorId) is { } namedLevel)
                    {
                        short fixedLevel = (short)Math.Clamp(namedLevel + Settings.GlobalOffset, 1, short.MaxValue);
                        ApplyLevel(scratch, fixedLevel);
                        scratch.Configuration.TemplateFlags &= ~NpcConfiguration.TemplateFlag.Stats;
                        wasChanged = true;
                        ++namedCount;
                        if (Settings.PrintDebugOutput) Console.WriteLine($"  {editorId}: named -> {fixedLevel}");
                    }
                    // Priority 3: civilians
                    else if (IsCivilian(getter, linkCache))
                    {
                        scratch.Configuration.Level = new PcLevelMult { LevelMult = 1f };
                        scratch.Configuration.CalcMinLevel = 1;
                        scratch.Configuration.CalcMaxLevel = 50;
                        wasChanged = true;
                        ++civiliansScaled;
                        if (Settings.PrintDebugOutput) Console.WriteLine($"  {editorId}: civilian -> PC-scaled cap 50");
                    }
                    // Priority 4: pipeline
                    else if (assessments.TryGetValue(getter.FormKey, out var assessment))
                    {
                        short newLevel = ComputeLevel(assessment, factionRanges, raceRanges, tierRanges, Settings);
                        ApplyLevel(scratch, newLevel);
                        scratch.Configuration.TemplateFlags &= ~NpcConfiguration.TemplateFlag.Stats;
                        wasChanged = true;
                        ++pipelineCount;
                    }

                    wasChanged |= RebalanceClassValues(scratch, state, linkCache);
                    wasChanged |= RelevelNPCSkills(scratch, linkCache);
                    wasChanged |= RelevelNPCStats(scratch, linkCache);
                    wasChanged |= DistributeNPCPerks(scratch, linkCache, GetVanillaCache(), excludedPerks);
                }

                if (wasChanged)
                {
                    // Get a minimal override — only the fields we actually changed
                    // are written. Everything else (body data, AI, combat style,
                    // factions, model paths, etc.) is left untouched.
                    var npcOverride = ctx.GetOrAddAsOverride(state.PatchMod);

                    // Level / configuration block
                    npcOverride.Configuration.Level        = scratch.Configuration.Level;
                    npcOverride.Configuration.CalcMinLevel = scratch.Configuration.CalcMinLevel;
                    npcOverride.Configuration.CalcMaxLevel = scratch.Configuration.CalcMaxLevel;
                    npcOverride.Configuration.TemplateFlags = scratch.Configuration.TemplateFlags;
                    npcOverride.Configuration.Flags         = scratch.Configuration.Flags;
                    npcOverride.Configuration.HealthOffset  = scratch.Configuration.HealthOffset;
                    npcOverride.Configuration.MagickaOffset = scratch.Configuration.MagickaOffset;
                    npcOverride.Configuration.StaminaOffset = scratch.Configuration.StaminaOffset;

                    // Class (only changed by RebalanceClassValues for humanoids)
                    if (!scratch.Class.Equals(getter.Class))
                        npcOverride.Class = scratch.Class;

                    // Skills
                    if (scratch.PlayerSkills is not null)
                    {
                        npcOverride.PlayerSkills ??= new PlayerSkills();
                        foreach (var (skill, val) in scratch.PlayerSkills.SkillValues)
                            npcOverride.PlayerSkills.SkillValues[skill] = val;
                    }

                    // Perks
                    npcOverride.Perks = scratch.Perks is { Count: > 0 }
                        ? scratch.Perks
                        : null;
                }

                ++npcsProcessed;
                if (npcsProcessed % 2000 == 0)
                    Console.WriteLine($"  ... {npcsProcessed} NPCs processed");
            }

            DisableExtraDamagePerks(state);
            StatScalerPatcher.Run(state, Settings);

            Console.WriteLine();
            Console.WriteLine("=== Skyrim Releveler Complete ===");
            Console.WriteLine($"  Total NPCs processed : {npcsProcessed}");
            Console.WriteLine($"  Releveled (pipeline) : {pipelineCount}");
            Console.WriteLine($"  Named overrides      : {namedCount}");
            Console.WriteLine($"  Civilians            : {civiliansScaled}");
            Console.WriteLine($"  Followers            : {followersScaled}");
        }
    }
}
